open-mmlab/mmdetection3d

- README.md
- docs/benchmarks.md
> Refactor readme

- docs/getting_started.md
> Fix path of getting_started

- .github/ISSUE_TEMPLATE/error-report.md
- .github/ISSUE_TEMPLATE/reimplementation_questions.md
Change mmdet to mmdet3d in issue templates
> Update issue templates

- mmdet3d/datasets/lyft_dataset.py
This bug seems to be fixed before but was rolled back for some reasons.
> Fix a minor bug in json2csv of lyft dataset

- mmdet3d/datasets/__init__.py
- mmdet3d/datasets/pipelines/__init__.py
- mmdet3d/datasets/pipelines/transforms_3d.py
- tests/test_pipeline/test_transforms_3d.py
Notice:
1. Add data aug op, BackgroundPointsFilter
2. Add unittest for BackgroundPointsFilter
> add data_aug BackgroundPointsFilter

- mmdet3d/datasets/__init__.py
> fix_dataset_init

- mmdet3d/ops/ball_query/ball_query.py
- mmdet3d/ops/ball_query/src/ball_query.cpp
- mmdet3d/ops/ball_query/src/ball_query_cuda.cu
- mmdet3d/ops/group_points/group_points.py
- mmdet3d/ops/pointnet_modules/point_sa_module.py
- tests/test_pointnet_ops.py
Notice:
1. Add OP `dilated ball query`
2. Update unittest for `dilated ball query`
> [feature]: support dilated ball query

- mmdet3d/apis/test.py
- fix problem of ProgressBar in multi-batch testing.
> [Fix] ProgressBar update problem

- mmdet3d/apis/inference.py
fix multi-batch bug in demo reported by #115
> [Fix] fix demo results bug

- .github/workflows/build.yml
- mmdet3d/datasets/custom_3d.py
- mmdet3d/datasets/dataset_wrappers.py
- mmdet3d/datasets/nuscenes_dataset.py
- mmdet3d/datasets/pipelines/dbsampler.py
- mmdet3d/datasets/pipelines/transforms_3d.py
- tests/test_dataset/test_dataset_wrappers.py
- tests/test_pipeline/test_transforms_3d.py
Fix label type bug when using database sampler for nuScenes dataset.
> [Fix]: fix label type bug when using dbsampler

- mmdet3d/models/detectors/base.py
- mmdet3d/models/detectors/mvx_two_stage.py
> [Fix]: bug in multi-batch show

- docs/install.md
- mmdet3d/__init__.py
Add version assert in init file.
> add-version-assert

- configs/centerpoint/centerpoint_01voxel_second_secfpn_4x8_cyclic_20e_nus.py
- configs/centerpoint/centerpoint_02pillar_second_secfpn_4x8_cyclic_20e_nus.py
Change centerpoint config file to support interval evaluation
> [fix]:add evaluation interval

- mmdet3d/core/voxel/voxel_generator.py
- mmdet3d/datasets/__init__.py
- mmdet3d/datasets/pipelines/__init__.py
- mmdet3d/datasets/pipelines/transforms_3d.py
- tests/test_pipeline/test_transforms_3d.py
1. Add dataset pipeline SweepPointSample;
2. Add related unittest.
> [Feature]:add sweep point sample

- mmdet3d/datasets/nuscenes_dataset.py
> use correct dataset for nuscenes mini evaluation

- docs/getting_started.md
Change preparing data part in 'getting started'
> [Fix]: fix missing page

- docker/Dockerfile
- docs/install.md
Add docker file to support using mmdetection3d with docker. The demo is tested and works fine.
Resolves https://github.com/open-mmlab/mmdetection3d/issues/22
> Support docker

- .dev_scripts/gather_models.py
> [Fix]: gather-models

- mmdet3d/models/detectors/mvx_two_stage.py
- mmdet3d/models/fusion_layers/point_fusion.py
Fix the image pad shape bug in PointFusion.
Resolves https://github.com/open-mmlab/mmdetection3d/issues/151
> [Fix]: fix image pad shape bug in PointFusion

- README.md
- docs/changelog.md
- mmdet3d/__init__.py
- mmdet3d/version.py
1. Update v0.6.1 change log
2. Fix version assertion in init file to be compatible with mmdet
3. Update version file
> Bump to v0.6.1

- mmdet3d/core/anchor/__init__.py
- mmdet3d/core/anchor/anchor_3d_generator.py
- mmdet3d/models/dense_heads/__init__.py
- mmdet3d/models/dense_heads/shape_aware_head.py
- mmdet3d/models/dense_heads/train_mixins.py
- tests/test_anchors.py
- tests/test_heads.py
1. Add shape-aware grouping head in SSN (Shape Signature Networks)
2. Support different feature map sizes for grouping classes in anchor generator
> [Feature] Add shape-aware grouping head in SSN

- README.md
- configs/pointpillars/README.md
- configs/regnet/hv_pointpillars_regnet-1.6gf_fpn_sbn-all_4x8_2x_nus-3d.py
- configs/ssn/README.md
- docs/model_zoo.md
- mmdet3d/models/dense_heads/anchor3d_head.py
Primitive PointPillars + shape-aware grouping head results on Lyft.
> [Feature] SSN benchmark on Lyft

- configs/_base_/models/hv_second_secfpn_waymo.py
- configs/second/README.md
- configs/second/hv_second_secfpn_sbn_2x16_2x_waymoD5-3d-3class.py
Minor adjustment for the SECOND benchmark on Waymo with better performance.
> [Enhance] Update SECOND benchmark on Waymo

- README.md
- configs/nuimages/README.md
Add the link of nuImages pages in README.md, thus users could find the usages of nuImages in a more clear manner.
> Add nuImages entry in README.md

- docs/stat.py
> update stat to classify papers

- docs/1_exist_data_model.md
- docs/2_new_data_model.md
- docs/data_preparation.md
- docs/tutorials/customize_dataset.md
- docs/tutorials/customize_models.md
- docs/useful_tools.md
Fix #270 and other relative paths/links in documentation.
> [Fix] Fix relative paths/links in documentation

- mmdet3d/core/bbox/structures/base_box3d.py
- mmdet3d/core/bbox/structures/cam_box3d.py
> fix issues with inplace modification of tensors in BaseInstance3DBoxes

- README.md
- README_zh-CN.md
> [Enhance] Add chinese version readme

- docs/faq.md
- docs/index.rst
[Enhance] Add FAQ for common problems
* Add FAQ for listing common problems
* Add the problem when import open3d and corresponding solution to FAQ
* Add the problem when import pycocotools and corresponding solution to FAQ
> [Enhance] Add FAQ for common problems

- configs/centerpoint/centerpoint_0075voxel_second_secfpn_4x8_cyclic_20e_nus.py
- configs/centerpoint/centerpoint_01voxel_second_secfpn_4x8_cyclic_20e_nus.py
- configs/centerpoint/centerpoint_02pillar_second_secfpn_4x8_cyclic_20e_nus.py
Fix missing `coord_type` in db-sampler config.
> [fix]: fix-dbsampler-config

- README.md
- README_zh-CN.md
> [Enhance] add citation format 

- docs/getting_started.md
- mmdet3d/__init__.py
modify mmcv version requirements
> upgrade mmcv version

- README.md
- README_zh-CN.md
- configs/regnet/README.md
- configs/votenet/README.md
- docs/model_zoo.md
- docs/tutorials/config.md
- docs/useful_tools.md
- mmdet3d/core/evaluation/seg_eval.py
- tests/test_data/test_pipelines/test_loadings/test_loading.py
- tools/analysis_tools/benchmark.py
Fix a link error in README file and several typos in comments and unittest files.
> [Fix] Fix typos and errors

- mmdet3d/models/voxel_encoders/voxel_encoder.py
Move one code out of the for-loop. Mentioned in #383. A re-created PR due to CLA.
> [Enhancement] Enhance in vfe_layers creation

- data/sunrgbd/README.md
- mmdet3d/datasets/sunrgbd_dataset.py
Updated SUNRGBD dataset doc to stress the additional requirements for training ImVoteNet; also changed the image path in SUNRGBD data loading for convenience.
> [Doc] SUNRGBD dataset doc update

- mmdet3d/core/post_processing/box3d_nms.py
> [Fix] box3d_multiclass_nms docstring

- mmdet3d/models/detectors/__init__.py
- mmdet3d/models/detectors/fcos_mono3d.py
- mmdet3d/models/detectors/single_stage_mono3d.py
This PR just targets at the overall framework of FCOS3D detector such that the development of different heads can be simultaneously started.
Related unit tests will be supplemented when the complete FCOS3D model is supported.
> [Feature] Support FCOS3D Detector

- .github/workflows/build.yml
> [Fix] Fix github CI check error

- mmdet3d/core/bbox/structures/cam_box3d.py
- mmdet3d/core/bbox/structures/depth_box3d.py
- mmdet3d/core/bbox/structures/lidar_box3d.py
To avoid confusion, modified the docstring of three coordinate systems, lidar, depth, and camera.
> [Doc] Temporarily fix docstring of three coordinate systems.

- configs/_base_/datasets/waymoD5-3d-3class.py
* Fix waymo config when loading point
> [Fix] Waymo loading error

- .github/ISSUE_TEMPLATE/error-report.md
- .github/ISSUE_TEMPLATE/reimplementation_questions.md
- configs/3dssd/README.md
- configs/centerpoint/README.md
- configs/dynamic_voxelization/README.md
- configs/fp16/README.md
- configs/h3dnet/README.md
- configs/mvxnet/README.md
- configs/parta2/README.md
- configs/second/README.md
- configs/ssn/README.md
- data/scannet/README.md
- data/sunrgbd/README.md
- docs/1_exist_data_model.md
- docs/getting_started.md
Two types of errors:
- code blocks without a blank line above/under it
- Title without a blank line under it
> [Enhance] Fix markdown linting errors

- configs/_base_/datasets/s3dis_seg-3d-13class.py
- configs/_base_/datasets/scannet_seg-3d-20class.py
- data/s3dis/collect_indoor3d_data.py
- data/scannet/batch_load_scannet_data.py
- data/scannet/load_scannet_data.py
- mmdet3d/datasets/custom_3d_seg.py
- setup.cfg
Some small errors, the modifications have been verified.
> [Fix] Fix small errors in seg dataset and cfgs

- configs/regnet/metafile.yml
* Removing the pwc without metric: hv_pointpillars_regnet-400mf_secfpn_sbn-all_4x8_2x_lyft-3d
> [Fix] Removing the pwc without metric

- MANIFEST.in
* Updating MANIFEST.in for MMCLI
> [Fix] Updating MANIFEST

- mmdet3d/datasets/lyft_dataset.py
- mmdet3d/datasets/nuscenes_dataset.py
- mmdet3d/datasets/nuscenes_mono_dataset.py
> [Fix] Fix evaluation bugs in Nus and Lyft datasets

- configs/fcos3d/README.md
See https://github.com/open-mmlab/mmdetection3d/pull/542#discussion_r637498393.
> [Enhance] Add visualization example and instruction to FCOS3D cfg page

- mmdet3d/apis/inference.py
> [Fix] Fix det demo bug

- docs/1_exist_data_model.md
- docs/tutorials/waymo.md
- docs/useful_tools.md
- mmdet3d/datasets/lyft_dataset.py
There is a bug and some typos in the doc of testing Lyft.
Fixed a bug, fixed some typos, and modified a to-be-deprecated parameter.  …
> [Fix] Fix Lyft test command in docs and made some refinements

- configs/3dssd/README.md
- configs/3dssd/metafile.yml
- tests/test_models/test_detectors.py
- tests/test_models/test_heads/test_heads.py
- tests/test_models/test_segmentors.py
- tests/test_runtime/test_apis.py
I found some bugs when performing unit tests.
I fixed those bugs.
If this PR introduces a new feature, it is better to list some use …
> [Fix] Fixed wrong config paths

- mmdet3d/models/detectors/imvotenet.py
To add reference in a function modified from the original repo of ImVoteNet.
A reference is added.
If this PR introduces a new …
> [Fix] Add reference in`sample_valid_seeds` function used by ImVoteNet

- tools/data_converter/indoor_converter.py
> [Fix] indoor_converter

- tools/data_converter/scannet_data_utils.py
> [Fix] ScanNet data creation

- MANIFEST.in
- configs/fcos3d/metafile.yml
- configs/imvoxelnet/metafile.yml
- model-index.yml
* Rename `model_zoo.yml` as `model-index.yml`
* Add metafiles of `fcos` and `imvoxelnet`
**Note**
Please check the `Architecture` in metafiles of `fcos` and `imvoxelnet` carefully.
> [Fix] Refine metafiles

- README.md
The current waymo dataset link in `readme.md` is wrong, this PR will fix it.
`readme.md`
2. The …
> [Fix]: Fix waymo dataset link in `readme`.

- docker/Dockerfile
> [Fix] open-mmlab project versions in Dockerfile

- docs/switch_language.md
- docs_zh-CN/switch_language.md
- requirements/docs.txt
> Fix Chinese Documentation and Sphinx Version Bug

- .dev_scripts/gather_models.py
- README.md
- configs/groupfree3d/README.md
- configs/groupfree3d/metafile.yml
- docs/model_zoo.md
Release 4 groupfree3d models on ScanNet dataset.
Publish 4 models on ScanNet dataset and provide README.md.
No. …
> [Enhance] Group-Free-3D Benchmark on ScanNet

- mmdet3d/core/bbox/iou_calculators/iou3d_calculator.py
- mmdet3d/core/bbox/structures/base_box3d.py
- mmdet3d/core/bbox/structures/box_3d_mode.py
- mmdet3d/core/bbox/structures/cam_box3d.py
- mmdet3d/core/bbox/structures/depth_box3d.py
- mmdet3d/core/bbox/structures/lidar_box3d.py
- mmdet3d/datasets/lyft_dataset.py
- mmdet3d/models/dense_heads/free_anchor3d_head.py
- mmdet3d/models/detectors/fcos_mono3d.py
- mmdet3d/models/detectors/imvotenet.py
I find several bugs in the auto-generated api docs in [readthedocs](https://mmdetection3d.readthedocs.io/en/latest/).
I will describe the modifications in several comments below. …
> [Fix] Fix several errors in docstring

- docs_zh-CN/demo.md
Add demo.md Chinese version.
Add demo.md Chinese version.
no.
no.
4. The documentation has been modified accordingly, …
> [Docs] Add demo.md Chinese Version

- data/s3dis/README.md
- docs/datasets/s3dis_sem_seg.md
> [Enhance] Add doc for S3DIS semantic segmentation data

- mmdet3d/core/visualizer/show_result.py
See [here](https://github.com/open-mmlab/mmdetection3d/pull/618#discussion_r675343806). In a word, I want to keep the same default value for all three visualization functions.
Change default value of `show` to `True`.
It's fine within our codebase after carefully checking mmdet3d. And I don't think users will call these functions because they are wrapped in some other functions, and the interface of those functions are not affected.
N.A
2. The …
> [Fix] Keep consistent interface for visualization functions

- setup.cfg
- tests/test_data/test_datasets/test_nuscenes_mono_dataset.py
Fix nuscenes_mono_dataset unit test due to #744 .
If this PR introduces a new feature, it is better to list some use cases here, and …
> [Fix] Fix nuscenes_mono_dataset unit test due to hack fix

- mmdet3d/datasets/builder.py
- setup.cfg
* Modify resource limit in order to avoid being killed frequently
> [Enhance] Modify resourse limit

- docs/demo.md
- docs_zh-CN/demo.md
Update the FCOS3D model link in the Demo doc.
> [Fix] Update the FCOS3D model link in the Demo doc

- mmdet3d/core/visualizer/show_result.py
Fix the missing default `bbox_mode` in the `show_multi_modality_result`.
> [Fix] Fix the missing default bbox_mode in the show_multi_modality_result

- README.md
- README_zh-CN.md
- docs/changelog.md
- docs/getting_started.md
- docs_zh-CN/getting_started.md
- mmdet3d/version.py
> Bump to v0.16.0

- configs/_base_/models/imvotenet_image.py
BC-breaking caused by https://github.com/open-mmlab/mmdetection/pull/5205
Please refer to the modification.
If this PR introduces a …
> [Fix] Fix config of ImVoteNet

- mmdet3d/apis/inference.py
> [Fix] Fix import error

- docs_zh-CN/tutorials/customize_dataset.md
* Add tutorials/customize_dataset.md Chinese version
> [Doc] Add tutorials/customize_dataset.md Chinese version 

- mmdet3d/apis/inference.py
> [Fix] Fix import bug

- README_zh-CN.md
* Fix `getting_started.md` link in `README_zh-CN`
> [Fix] Fix getting_started.md link in README_zh-CN

- mmdet3d/core/bbox/coders/__init__.py
- mmdet3d/core/bbox/coders/point_xyzwhlr_bbox_coder.py
- tests/test_utils/test_bbox_coders.py
Add a new bbox coder `PointXYZWHLRBBoxCoder`  to support PointRCNN. It is an Point based Bbox Coder for 3D boxes.
> [Feature] PointXYZWHLRBBoxCoder

- configs/centerpoint/centerpoint_0075voxel_second_secfpn_dcn_4x8_cyclic_tta_20e_nus.py
- configs/free_anchor/hv_pointpillars_regnet-1.6gf_fpn_sbn-all_free-anchor_strong-aug_4x8_3x_nus-3d.py
- configs/free_anchor/hv_pointpillars_regnet-3.2gf_fpn_sbn-all_free-anchor_strong-aug_4x8_3x_nus-3d.py
> [Fix] Fix 3 unworking configs

- configs/centerpoint/centerpoint_0075voxel_second_secfpn_dcn_4x8_cyclic_tta_20e_nus.py
- mmdet3d/models/detectors/centerpoint.py
> [Fix] Fix Centerpoint test-time augmentation

- .github/workflows/build.yml
- setup.py
Support python3.9
Add python3.9 in CI
No
> [Feature] Add python3.9 in CI

- README.md
- README_zh-CN.md
- docs/changelog.md
- docs/getting_started.md
- docs_zh-CN/getting_started.md
- mmdet3d/version.py
> Bump to v0.17.0

- .github/workflows/build.yml
- requirements/docs.txt
- setup.py
As recommended, we should fix the version of sphinx.
Fix the version of sphinx
> [Docs] Fix the version of sphinx

- docs/2_new_data_model.md
update waymo dataset tutorial link in 2_new_data_model.md
update waymo dataset tutorial link in 2_new_data_model.md
no
n/a
> [Fix] update waymo dataset tutorial link

- mmdet3d/core/bbox/coders/__init__.py
- mmdet3d/core/bbox/coders/fcos3d_bbox_coder.py
- mmdet3d/core/bbox/coders/pgd_bbox_coder.py
- tests/test_utils/test_bbox_coders.py
Support PGD bounding box coder.
- Add PGD BBox Coder and its unit test.
- Fix several typos and refine related variable names.
No.
If …
> [Feature] PGD BBox Coder

- mmdet3d/core/visualizer/image_vis.py
fix image_vis.py  to support kitti dataset visualization
fix image_vis.py  to support kitti dataset visualization …
> [Fix] Fix visualization in KITTI dataset

- .github/workflows/build.yml
Use docker to accelerate CI.
Modify the docker usage in the build.yml (CI) and remove the original related environment settings.
If …
> [Enhancement] Use docker to accelerate CI

- mmdet3d/core/bbox/structures/cam_box3d.py
- mmdet3d/core/bbox/structures/depth_box3d.py
- mmdet3d/core/bbox/structures/lidar_box3d.py
> typo for bbox origin 

- docs/compatibility.md
Update necessary compatibility info regarding the coordinate system refactoring.
Added a section in compatibility docs.
If this PR …
> [Doc] Update compat doc on coord sys refactoring

- docker/Dockerfile
Update mmcv version in dockerfile to fix the incompatibility problem.
Update mmcv version in dockerfile to fix the incompatibility problem.
1. Pre-commit or other linting tools …
> [Fix] Update mmcv version in dockerfile

- mmdet3d/apis/inference.py
Fix the memory-leak problem in `init_detector` by always mapping the weights to cpu.
Follow the similar issue [#6405](https://github.com/open-mmlab/mmdetection/pull/6405) in mmdetection.
If so, please describe how it breaks the compatibility and how the downstream projects should …
> [Fix] Fix the memory-leak problem in init_detector

- mmdet3d/apis/__init__.py
- mmdet3d/apis/train.py
- tools/train.py
Set a random seed when the user does not set a seed.
Add an `init_random_seed` function and call this function when training.
If this …
> [Enchance] Set a random seed when the user does not set a seed.

- README.md
- README_zh-CN.md
add mmflow into readme.
add mmflow into readme.
no
n/a
> [Doc] Add MMFlow into README

- mmdet3d/models/voxel_encoders/pillar_encoder.py
#981 
Fix PointPillars FLOPs calculation indexing error
2. The modification is covered by complete …
> [Fix] Fix PointPillars FLOPs calculation error

- mmdet3d/models/voxel_encoders/pillar_encoder.py
#981 
Fix PointPillars FLOPs calculation error for master branch
2. The modification is covered by …
> [Fix] Fix PointPillars FLOPs calculation error for master branch

- README.md
- README_zh-CN.md
add mmhuman3d in readme
add mmhuman3d in readme
2. The modification is covered by complete unit …
> [Enhance] add mmhuman3d in readme

- README.md
- README_zh-CN.md
- docs/conf.py
- docs_zh-CN/conf.py
fix mmhuman3d reference
fix mmhuman3d reference
2. The modification is covered by complete unit …
> [Enhance] fix mmhuman3d reference

- setup.py
Solve the exception raised by `os.symlink` on Windows.
Solve the exception raised by `os.symlink` on Windows.
If this PR introduces a …
> [Fix] Catch symlink failure on Windows

- .pre-commit-config.yaml
Replace the third-party markdownlint hook with official and add codespell hook.
Update .pre-commit-config.yaml …
> [Enhance] Use the official markdownlint hook and add codespell hook

- .github/workflows/build.yml
Ignore paths in `.github/workflows/build.yml`.
Ignore paths in `.github/workflows/build.yml`.
If this PR introduces a new feature, it …
> [Enhance] Ignore paths

- .github/workflows/build.yml
- .github/workflows/deploy.yml
Cancel previous runs that are not completed for a given workflow.
Cancel previous runs that are not completed for a given workflow. …
> [Enhance] Cancel previous runs that are not completed

- .github/workflows/build.yml
- .github/workflows/lint.yml
Extract lint.yml.
Extract lint.yml. …
> [Fix] Extract lint.yml

- docs/conf.py
- docs_zh-CN/conf.py
This PR uses shared menu content from OpenMMLab's theme and removes duplicated contents from config, saving efforts on routine menu maintenance.
conf.py under docs and docs-zh-CN …
> [Doc] use shared menu from theme

- .readthedocs.yml
- docs/conf.py
- docs_zh-CN/conf.py
- requirements/docs.txt
- requirements/readthedocs.txt
Fix API documentation compilation and mmcv build errors.
Note: PDF doc compilation can be fixed in another PR.
- Simplify and fix requirements of compiling the documentation.
- Replace mmcv-full with mmcv and add corresponding mocked mmcv.ops to avoid related erros.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their …
> [Fix] Fix API documentation compilation and mmcv build errors

- configs/point_rcnn/README.md
- configs/point_rcnn/metafile.yml
- docs/model_zoo.md
- docs_zh-CN/model_zoo.md
Support PointRCNN KITTI benchmark.
Add README.md and metafile.yml, and modify model_zoo.md.
If this PR introduces a new feature, it …
> [Feature] Support PointRCNN KITTI benchmark

- README.md
- README_zh-CN.md
- configs/h3dnet/README.md
- configs/votenet/README.md
- docs/en/conf.py
- docs/en/datasets/lyft_det.md
- docs/en/datasets/scannet_sem_seg.md
- docs/en/demo.md
Fix docs link.
Change paths for docs link.
If this PR introduces a new feature, it is better to list some use cases here, and update …
> [Fix] Fix docs link

- tools/data_converter/sunrgbd_data_utils.py
Fix SUN RGB-D generation
Supply dimension information.
If this PR introduces a new feature, it is better to list some use cases here, …
> [Fix] Fix SUN RGB-D generation

- README.md
- README_zh-CN.md
> [Enhance] add mmrazor, mmselfsup and mmdeploy in readme

- README.md
- README_zh-CN.md
> [Doc] add OpenMMLab website and platform links

- configs/regnet/metafile.yml
Update RegNet metafile.
Remove `Collections` from RegNet metafile.
If this PR introduces a new feature, it is better to list some use …
> [Fix] Update regnet metafile

- mmdet3d/core/points/base_points.py
Fix axis=0 rotation in master branch, the axis= 0 rotation could be not used in our models before. …
> [Fix] Fix axis=0 rotation in master branch

- mmdet3d/datasets/pipelines/transforms_3d.py
> [Enhance] support semantic seg in Flip3D augmentation

- docs/en/faq.md
- docs/zh_cn/faq.md
add point cloud annotation in FAQ
1. Pre-commit or other linting tools are used to fix …
> [Doc] add point cloud annotation in FAQ

- mmdet3d/core/bbox/structures/cam_box3d.py
- mmdet3d/core/bbox/structures/depth_box3d.py
- mmdet3d/core/bbox/structures/lidar_box3d.py
Fix corner bug in different coordinates.
Remove `assert` in different coordinates.
If this PR introduces a new feature, it is better …
> [Fix] Fix corner bug in different coordinates

- docs/en/datasets/waymo_det.md
- docs/zh_cn/datasets/waymo_det.md
update bazel version to fix the bug while build binary file for waymo metrics computation 
update bazel version to fix the bug while build binary file for waymo metrics computation  …
> [Fix] update bazel version to fix the bug while build binary file for waymo metrics computation 

- configs/_base_/default_runtime.py
- mmdet3d/utils/__init__.py
- mmdet3d/utils/setup_env.py
- setup.cfg
- tests/test_utils/test_setup_env.py
- tools/test.py
- tools/train.py
Use `multiprocessing` to accelerate training.
Add `multiprocessing` in `train.py`.
If this PR introduces a new feature, it is better …
> [Enhance] Accelerate training

- configs/monoflex/README.md
- configs/monoflex/metafile.yml
- docs/en/model_zoo.md
- docs/zh_cn/model_zoo.md
> [Feature] add monoflex benchmark

- demo/inference_demo.ipynb
change import `init_detector` to ` init_model` in inference_demo.ipynb.
change import `init_detector` to ` init_model` in inference_demo.ipynb.
1. Pre-commit or other linting …
> [Fix] fix import `init_detector` error inference_demo.ipynb

- mmdet3d/ops/group_points/group_points.py
- tests/test_models/test_common_modules/test_pointnet_ops.py
fix CI in dev branch caused by merging master branch to dev branch operation.
1. Pre-commit or other linting tools …
> [Fix] fix ci in dev branch

- mmdet3d/core/points/base_points.py
There is an index bug in the method in_range_bev() of class BasePoints, which may lead to the misjudgement of valid points.
Fix this index bug in mmdet3d/core/points/base_points.py.
No. This bug …
> [Fix] Fix an index bug in the class BasePoints

- mmdet3d/ops/spconv/conv.py
Force to use mmdet3d's spconv
Set `force=True` when registering the spconv into CONV_LAYERS.
2. …
> [Fix] Force to use mmdet3d's spconv

- mmdet3d/ops/spconv/conv.py
> Force to use mmdet3d's spconv

- README.md
- README_zh-CN.md
fix README Point R-CNN link missing.
fix README Point R-CNN link missing.
2. The modification is …
> [Fix] fix README Point R-CNN link missing

- docs/en/1_exist_data_model.md
- docs/zh_cn/1_exist_data_model.md
> [Fix] Fix typo in 1_exist_data_model docs

- docs/zh_cn/getting_started.md
add step _f. clone MMDetection repo_ into zh_cn/getting_started.md
> fixed docs/zh_cn/getting_started

- docs/en/model_zoo.md
- docs/zh_cn/model_zoo.md
> [Docs] update fp16 links in model_zoo.md

- docs/en/getting_started.md
- docs/zh_cn/getting_started.md
Fix the incorrect mmcv/mmdet/mmseg installation version in the instruction.
Fix the incorrect mmcv/mmdet/mmseg installation version in the instruction.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep …
> [Fix] Fix the mmcv/mmdet/mmseg installation version in getting_started

- mmdet3d/models/middle_encoders/pillar_scatter.py
something wrong when i use the function middle_encoder.pillar_scatter.forward_single
change the index of coors in line 53
> [Fix] Fix the wrong index of coor in middle_encoder.pillar_scatter.forward_single

- mmdet3d/datasets/pipelines/transforms_3d.py
Remove PointSample constraint.
Remove PointSample constraint in which point must be a CameraPoints type.
If this PR introduces a new …
> [Fix] Remove PointSample constraint

- .github/workflows/build.yml
- mmdet3d/datasets/pipelines/loading.py
- tests/test_data/test_datasets/test_lyft_dataset.py
- tests/test_data/test_datasets/test_s3dis_dataset.py
- tests/test_data/test_datasets/test_scannet_dataset.py
- tests/test_data/test_datasets/test_sunrgbd_dataset.py
Add Windows CI after moving ops
Add Windows CI after moving ops
2. The modification is covered by …
> [Enhance] Add Windows CI after moving ops

- docs/en/getting_started.md
- docs/zh_cn/getting_started.md
This PR adds brief installation instructions to the README file to help users get started quickly
README.md & README_zh-CN.md
None
> Add install command to readme

- docs/en/tutorials/backends_support.md
- docs/en/tutorials/index.rst
- docs/zh_cn/tutorials/backends_support.md
- docs/zh_cn/tutorials/index.rst
- mmdet3d/datasets/custom_3d.py
- mmdet3d/datasets/custom_3d_seg.py
- mmdet3d/datasets/kitti_dataset.py
- mmdet3d/datasets/lyft_dataset.py
- mmdet3d/datasets/nuscenes_dataset.py
- mmdet3d/datasets/pipelines/dbsampler.py
- mmdet3d/datasets/s3dis_dataset.py
- mmdet3d/datasets/scannet_dataset.py
- mmdet3d/datasets/sunrgbd_dataset.py
- mmdet3d/datasets/waymo_dataset.py
Support load annotations from ceph for datasets and dbsampler
Support load annotations from ceph for datasets and dbsampler
1. Pre-commit or other linting tools are used to fix …
> [Enhance] Support load annotations from ceph

- mmdet3d/__init__.py
- tools/misc/browse_dataset.py
fix browse dataset and mmcv max version.Refer to [pr#1277.](https://github.com/open-mmlab/mmdetection3d/pull/1277).
fix browse dataset script and mmcv max version.
> [Fix]fix browse dataset and mmcv max version

- docs/en/conf.py
- docs/zh_cn/conf.py
- requirements/docs.txt
Following https://github.com/open-mmlab/mmcv/pull/1287, use myst-parser so that we can beautify the doc in the future.
- modified:   docs/en/conf.py
- modified:   docs/zh_cn/conf.py
- modified:   requirements/docs.txt
N/A
If this PR introduces a new feature, it is better to list some use cases here and update the documentation.
3. If …
> Replace recommonmark with myst_parser

- tools/misc/fuse_conv_bn.py
> Fix import error in fuse_conv_bn.py

- docs/en/tutorials/model_deployment.md
- docs/zh_cn/tutorials/model_deployment.md
> Improve the documentation of model_deployment

- docs/zh_cn/supported_tasks/lidar_sem_seg3d.md
> [Docs] Add chinese documentation of lidar_sem_seg3d

- docs/en/tutorials/customize_datasetv2.md
- docs/en/tutorials/index.rst
- docs/en/tutorials/pure_point_cloud_dataset.md
- mmdet3d/datasets/custom_3d.py
- mmdet3d/datasets/semantickitti_dataset.py
support pure point cloud custom data training and add corresponding new tutorial
support pure point cloud custom data training and add corresponding new tutorial …
> [Enhance] support pure point cloud custom data training and add docs

- .github/workflows/build.yml
- tests/test_utils/test_compat_cfg.py
Follows https://github.com/open-mmlab/mmocr/pull/988
N/A
N/A
> Fix GPG key error in CI

- mmdet3d/models/builder.py
> Fix potential bug of build roi_extractors

- mmdet3d/datasets/pipelines/compose.py
fix the bug for config like 'mmdet3d.loadImageFromMono3D'  …
> [Fix] fix compose pipeline potential bug

- configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py
- configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py
This PR is created as I findthat the updated training logs and model checkpoints are little different from the corresponding config files, which will make users can not reproduce the results provided.
> Update hv_pp_kitti config

- docs/en/supported_tasks/vision_det3d.md
- docs/zh_cn/supported_tasks/vision_det3d.md
> [Docs] Add Chinese documentation of vision_det3d

- mmdet3d/ops/spconv/overwrite_spconv/__init__.py
* Add a __init__.py to overwrite_spconv
* fix bug
If this PR introduces a new feature, it is better to list some use cases here, and …
> [Fix] Make overwrite_spconv packaged when build whl (#1477)

- docs/en/faq.md
- docs/en/getting_started.md
Following the [pull request in mmdet](https://github.com/open-mmlab/mmdetection/pull/7897), reorganize the installation guide:
```
```
> [Enhance] update the installation and faq doc

- setup.py
+ Add mim to extras_require in setup.py
+ Update setup.py
No
4. The documentation has been modified …
> Add mim to extras_require in setup.py 

- .pre-commit-config.yaml
+ Fix the mdformat version
+ .pre-commit-config.yaml
No
4. The documentation has been modified accordingly, …
> [Enhance] Fix mdformat version

- mmdet3d/models/roi_heads/__init__.py
> Fix module not registered bug

- requirements/docs.txt
> [Fix]Fix markdown version

- configs/nuimages/metafile.yml
- configs/second/metafile.yml
- configs/votenet/metafile.yml
> [Fix] fix metafile and add weight model

- mmdet3d/models/necks/__init__.py
- mmdet3d/models/necks/view_transformer.py
- tests/test_models/test_necks/test_necks.py
Support lift-splat-shoot view transformer
+ mmdet3d/models/necks/view_transformer.py
Does the modification introduce changes that break the back-compatibility of the downstream repos? no
If this PR introduces a new feature, it is better to list some use cases here, and update the documentation. 
will add bevdet afterward …
> support lift-splat-shoot view transformer

- configs/ssn/hv_ssn_regnet-400mf_secfpn_sbn-all_1x16_2x_lyft-3d.py
- configs/ssn/hv_ssn_regnet-400mf_secfpn_sbn-all_2x16_2x_nus-3d.py
- configs/ssn/hv_ssn_secfpn_sbn-all_2x16_2x_lyft-3d.py
Fix ssn config.
2. The modification …
> [Fix] Fix ssn

- configs/nuimages/metafile.yml
We need to support `README: https://github.com/open-mmlab/mmdetection/blob/master/configs/cascade_rcnn/README.md`. …
> [Fix] Fix the cross-codebase reference problem in metafile README

- README.md
- README_zh-CN.md
- configs/fcaf3d/metafile.yml
Small fixes in `.yml` and `.md` files after fcaf3d pr.
Fix fcaf3d weights links in `metafile.yml`. Fix `✗` in readme.
No
Can this pr be applied directly to master branch?
> [Fix] Small fixes in `.yml` and `.md` files after fcaf3d pr

- mmdet3d/__init__.py
- requirements/mminstall.txt
> [Fix] fix mim version

- demo/inference_demo.ipynb
clear demo ipynb file output
clear demo ipynb file output
2. The modification is covered by …
> [Fix] clear demo ipynb file output

- model-index.yml
> [Fix] fix model_index.yml

- mmdet3d/registry.py
> [Fix] add log processor in registry

- tools/test.py
- tools/train.py
Fix tools for test-1.x branch
2. The modification is …
> Fix tools for test-1.x branch

- .circleci/test.yml
change `mmocr` in circle ci to `mmdet3d`.
1. Pre-commit or other linting tools are …
> [Fix] update Circle CI

- configs/_base_/datasets/waymoD5-3d-3class.py
- configs/_base_/datasets/waymoD5-3d-car.py
- mmdet3d/evaluation/functional/waymo_utils/prediction_kitti_to_waymo.py
- mmdet3d/evaluation/metrics/waymo_metric.py
- mmdet3d/utils/misc.py
> [Fix] fix waymo training and eval bug

- configs/_base_/datasets/scannet_seg-3d-20class.py
- configs/paconv/paconv_cuda_ssg_8x8_cosine_200e_s3dis_seg-3d-13class.py
- configs/paconv/paconv_ssg_8x8_cosine_150e_s3dis_seg-3d-13class.py
- configs/pointnet2/pointnet2_msg_16x2_cosine_250e_scannet_seg-3d-20class.py
- configs/pointnet2/pointnet2_msg_16x2_cosine_80e_s3dis_seg-3d-13class.py
- configs/pointnet2/pointnet2_msg_xyz-only_16x2_cosine_250e_scannet_seg-3d-20class.py
- configs/pointnet2/pointnet2_ssg_16x2_cosine_200e_scannet_seg-3d-20class.py
- configs/pointnet2/pointnet2_ssg_xyz-only_16x2_cosine_200e_scannet_seg-3d-20class.py
update part of seg config
update part of seg config
2. The modification is covered by complete …
> [Fix] update part of seg config

- .dev_scripts/gather_models.py
- mmdet3d/apis/inference.py
- mmdet3d/datasets/det3d_dataset.py
- mmdet3d/datasets/kitti2d_dataset.py
- mmdet3d/datasets/seg3d_dataset.py
- mmdet3d/datasets/transforms/dbsampler.py
- mmdet3d/datasets/transforms/loading.py
- mmdet3d/evaluation/functional/lyft_eval.py
- mmdet3d/evaluation/metrics/kitti_metric.py
- mmdet3d/evaluation/metrics/lyft_metric.py
- mmdet3d/evaluation/metrics/nuscenes_metric.py
- mmdet3d/evaluation/metrics/waymo_metric.py
- mmdet3d/utils/setup_env.py
- tools/dataset_converters/indoor_converter.py
- tools/dataset_converters/kitti_converter.py
- tools/dataset_converters/lyft_converter.py
- tools/dataset_converters/nuimage_converter.py
- tools/dataset_converters/nuscenes_converter.py
- tools/dataset_converters/s3dis_data_utils.py
- tools/dataset_converters/scannet_data_utils.py
- tools/dataset_converters/update_infos_to_v2.py
- tools/misc/visualize_results.py
- tools/update_data_coords.py
Replace mmcv.fileclient to mmengine.fileclient. …
> [FIx]Replace mmcv.fileclient to mmengine.fileclient

- docs/en/changelog.md
- docs/zh_cn/faq.md
- docs/zh_cn/getting_started.md
update the getting_started in cn doc.
> [Fix] Update the cn doc

- demo/mono_det_demo.py
- demo/multi_modality_demo.py
- demo/pc_seg_demo.py
- demo/pcd_demo.py
- mmdet3d/apis/inference.py
> [Fix] fix init_model_api for 1.x model

- mmdet3d/models/layers/norm.py
- mmdet3d/models/layers/spconv/__init__.py
- mmdet3d/models/layers/spconv/overwrite_spconv/write_spconv2.py
- mmdet3d/models/layers/transformer.py
Remove dependency on MMCV registry and fix spconv.
Define the spconv2.0 module's metadata to determine spconv version. If used mmcv spconv training model, and want to use spconv2.0 inference model, need to transpose the module's dim.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with …
> [Fix] Remove dependency on MMCV registry and fix spconv

- mmdet3d/datasets/convert_utils.py
- mmdet3d/datasets/dataset_wrappers.py
- mmdet3d/datasets/nuscenes_dataset.py
- mmdet3d/evaluation/metrics/nuscenes_metric.py
- tools/dataset_converters/lyft_converter.py
- tools/dataset_converters/nuscenes_converter.py
Fix nus metric and cbgs.
2. The …
> [Fix]Fix nus metric and cbgs

- mmdet3d/datasets/waymo_dataset.py
- mmdet3d/evaluation/metrics/waymo_metric.py
- mmdet3d/utils/misc.py
… evaluation
Add METAINFO for waymo dataset and support file_client_args for waym
1. Pre-commit or other linting …
> [Fix]  Add METAINFO for waymo dataset and support file_client_args for waymo

- docs/en/advanced_guides/supported_tasks/vision_det3d.md
> [Doc] update `vision_det3d.md` doc

- configs/_base_/default_runtime.py
- mmdet3d/engine/hooks/__init__.py
- mmdet3d/engine/hooks/visualization_hook.py
- tests/test_engine/test_hooks/test_visualization_hook.py
- tools/test.py
> [Refactor] update visualization hook

- mmdet3d/engine/__init__.py
- mmdet3d/utils/setup_env.py
> [Fix]Fix hook register

- README.md
- README_zh-CN.md
> [Docs]Docs readme

- .github/workflows/deploy.yaml
> [Fix]Add deploy.yaml

- mmdet3d/utils/setup_env.py
When runing the configs, it may report an error that `** is not in the model registry.`, and the PR is created to fix the bug.
> [Fix] Fix the bug that `model not registered`

- tools/misc/browse_dataset.py
> [Fix] update `browse_dataset` due to dataflow refactor

- mmdet3d/datasets/transforms/transforms_3d.py
> [Fix] fix dbsampler bug to use ground plane data

- .github/workflows/deploy.yaml
- mmdet3d/apis/inference.py
Fix inference detector to add timestamp key.
1. Pre-commit or other linting tools are used to fix the potential lint …
> [Fix]Fix inference detector

- tools/dist_train.sh
> [Fix] Fix distributed training bug

- configs/fcos3d/fcos3d_r101-caffe-dcn_fpn_head-gn_8xb2-1x_nus-mono3d.py
- mmdet3d/datasets/det3d_dataset.py
- mmdet3d/datasets/nuscenes_dataset.py
> [Fix] fix nuscenes datasets

- configs/_base_/datasets/kitti-3d-3class.py
- configs/benchmark/hv_PartA2_secfpn_4x8_cyclic_80e_pcdet_kitti-3d-3class.py
- configs/benchmark/hv_pointpillars_secfpn_3x8_100e_det3d_kitti-3d-car.py
- configs/benchmark/hv_pointpillars_secfpn_4x8_80e_pcdet_kitti-3d-3class.py
- configs/benchmark/hv_second_secfpn_4x8_80e_pcdet_kitti-3d-3class.py
- mmdet3d/engine/__init__.py
- mmdet3d/engine/hooks/__init__.py
- mmdet3d/engine/hooks/benchmark_hook.py
> [Refactor] update benchmark config

- mmdet3d/structures/bbox_3d/box_3d_mode.py
- mmdet3d/structures/bbox_3d/coord_3d_mode.py
- mmdet3d/structures/bbox_3d/depth_box3d.py
> [Docs] Update docs

- .circleci/test.yml
- docs/en/getting_started.md
- docs/zh_cn/getting_started.md
- mmdet3d/models/data_preprocessors/data_preprocessor.py
- requirements/optional.txt
waymo-open-dataset-tf-2-6-0 requires python>=3.7  …
> Modify the min version of python to 3.7 in CI & update docs

- docs/en/advanced_guides/datasets/lyft_det.md
- docs/en/advanced_guides/datasets/scannet_det.md
- docs/en/advanced_guides/datasets/sunrgbd_det.md
Fix the doc of sunrgbd dataset and lyft dataset
> [Refactor]fix sunrgb lyft doc

- mmdet3d/datasets/det3d_dataset.py
- mmdet3d/datasets/kitti_dataset.py
- mmdet3d/datasets/lyft_dataset.py
- mmdet3d/datasets/nuscenes_dataset.py
- mmdet3d/datasets/scannet_dataset.py
- mmdet3d/datasets/sunrgbd_dataset.py
- mmdet3d/datasets/waymo_dataset.py
- tools/dataset_converters/update_infos_to_v2.py
For 3D detection task on nuscenes dataset, the key `num_pts_feats` is not included in the `info`.
> [Fix]: Fix nuscenes dataset training

- .pre-commit-config.yaml
- docs/en/advanced_guides/customize_runtime.md
- docs/en/user_guides/config.md
- mmdet3d/datasets/transforms/dbsampler.py
- mmdet3d/datasets/transforms/formating.py
- mmdet3d/datasets/transforms/loading.py
- mmdet3d/datasets/transforms/test_time_aug.py
- mmdet3d/datasets/transforms/transforms_3d.py
- mmdet3d/models/builder.py
- mmdet3d/models/detectors/dynamic_voxelnet.py
- mmdet3d/models/layers/transformer.py
- mmdet3d/models/middle_encoders/sparse_encoder.py
- setup.cfg
- tests/test_structures/test_bbox/test_box3d.py
The motivation to upgrade some versions of pre-commit hooks to latest is that importlib-metadata v5.0.0 which removed deprecated endpoint breaks the flake8. More details at https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean/73932581#73932581.
Upgrade pre-commit-hook in the dev-1.x branch
If so, please describe how it breaks the compatibility and how the downstream projects should …
> Upgrade pre-commit-hook in the dev-1.x branch

- .github/workflows/lint.yml
- .pre-commit-config.yaml
- configs/sassd/README.md
- mmdet3d/models/builder.py
- mmdet3d/models/middle_encoders/sparse_encoder.py
- mmdet3d/models/model_utils/transformer.py
- setup.cfg
- tests/test_utils/test_box3d.py
The motivation to upgrade some versions of pre-commit hooks to latest is that importlib-metadata v5.0.0 which removed deprecated endpoint breaks the flake8. More details at https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean/73932581#73932581.
Upgrade some versions of pre-commit hooks in the dev branch.
If so, please describe how it breaks the compatibility and how the downstream …
> Upgrade pre-commit-hook in the dev branch

- docs/en/data_preparation.md
**Motivation**
Unable to run the command without additional <job_name> argument for an environment with slurm.
**Modification**
Added job_name placeholder argument to indicate it has to be added when running the command.
**Use Case**
sh tools/create_data.sh long create_data kitti
##
##
Does the modification introduce changes that break the back-compatibility of the downstream …
> Added job_name argument for data preparation in environment using slurm

- .circleci/test.yml
- requirements/optional.txt
> [CI] Fix CI on cuda env

- configs/_base_/datasets/waymoD5-3d-3class.py
- mmdet3d/datasets/transforms/formating.py
- mmdet3d/datasets/transforms/loading.py
- mmdet3d/datasets/transforms/transforms_3d.py
fix data loading, formating bugs and dataset path
mmdet3d/datasets/transforms/loading.py
mmdet3d/datasets/transforms/formating.py
mmdet3d/datasets/transforms/transform_s3d.py
configs/_base_/datasets/waymoD5-3d-3class.py
If this PR introduces a new feature, it is better to list some use …
> [Fix] Fix data preprocessing conflicts

- README.md
- README_zh-CN.md
- docs/en/changelog.md
- docs/en/faq.md
- mmdet3d/version.py
> Bump to 1.0.0rc5

- .github/workflows/build.yml
Fix the installation of  pycocotools like  https://github.com/open-mmlab/mmaction2/pull/1831 …
> [CI] Fix the installation of  pycocotools

- configs/_base_/datasets/waymoD5-mono3d-3class.py
- configs/pgd/pgd_r101_fpn-head_dcn_16xb3_waymoD5-mono3d.py
- mmdet3d/datasets/waymo_dataset.py
- mmdet3d/evaluation/metrics/waymo_metric.py
Update task name and config for fcos3d++ on waymo
waymo_dataset.py
waymo_metric.py
> [Fix] Update task name and config for fcos3d++ on waymo

- mmdet3d/evaluation/metrics/seg_metric.py
- tests/test_evaluation/test_metrics/test_seg_metric.py
Use MMEval MeanIoU. Besides we add more display results info and update the display format like below:
1. Pre-commit …
> [Refactor] Use `mmeval.MeanIoU` for `SegMetric`

- README.md
- README_zh-CN.md
- mmdet3d/evaluation/metrics/seg_metric.py
- tests/test_evaluation/test_metrics/test_seg_metric.py
> [Docs] Add mmyolo link in README

- mmdet3d/datasets/s3dis_dataset.py
- mmdet3d/datasets/seg3d_dataset.py
- mmdet3d/evaluation/metrics/seg_metric.py
- tests/test_datasets/test_scannet_dataset.py
- tests/test_evaluation/test_metrics/test_seg_metric.py
> [Fix] fix circle ci due to seg

- mmdet3d/evaluation/functional/waymo_utils/prediction_kitti_to_waymo.py
The IO module in `tensorflow` after 2.6.0 is split to `tensorflow-io`.
Please setup your s3 setting by referring to https://docs.w3cub.com/tensorflow~guide/deploy/s3
If this PR introduces a new feature, it is better to list …
> [Enhance] Support evaluation for waymo dataset on s3 filesystem when tensorflow>=2.6.0

- tools/dataset_converters/update_infos_to_v2.py
> --pkl -> --pkl-path

- docs/en/advanced_guides/customize_dataset.md
The motivation of this PR is to add an example of pcd to bin format file.
- customize_datasets.md  
Added installation examples and code examples for converting pcd to bin files using the pypcd tool in this document.
No.
> [Enhance] Add an example of pcd to bin format.

- README.md
- README_zh-CN.md
> [Enhance] Add MMEval in README

- tools/dataset_converters/update_infos_to_v2.py
> [Fix]: Rename `CLASSES` with `classes` in converter

- configs/centerpoint/centerpoint_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d.py
- mmdet3d/datasets/det3d_dataset.py
> [Fix] Fix instance statistics in Det3DDataset when only detecting a single class

- tools/create_data.py
> [Enhance] Remove useless `json` file converter

- mmdet3d/models/layers/pointnet_modules/stack_point_sa_module.py
- mmdet3d/models/roi_heads/bbox_heads/pv_rcnn_bbox_head.py
Fix a bug in the stack SA module to make QueryAndGroup ops have consistent output nums. …
> [Fix]Fix a bug in StackQueryAndGroup

- configs/_base_/datasets/lyft-3d-range100.py
- configs/_base_/datasets/nuim-instance.py
- configs/centerpoint/README.md
- configs/nuimages/htc_r50_fpn_1x_nuim.py
- configs/nuimages/mask-rcnn_r50_caffe_fpn_1x_nuim.py
- configs/nuimages/mask-rcnn_r50_caffe_fpn_coco-3x_1x_nuim.py
- configs/nuimages/mask-rcnn_r50_caffe_fpn_coco-3x_20e_nuim.py
- configs/nuimages/mask-rcnn_r50_fpn_coco-2x_1x_nus-2d.py
- configs/parta2/PartA2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-car.py
- configs/pgd/pgd_r101-caffe_fpn_head-gn_16xb2-1x_nus-mono3d.py
- tools/dataset_converters/update_infos_to_v2.py
> [FIX] replace DefaultFormatBundle/3D with Pack(3D)DetInputs

- mmdet3d/evaluation/metrics/__init__.py
> [FIX] fixkeyword

- docs/en/getting_started.md
- docs/zh_cn/getting_started.md
> [Docs] Update getting started

- projects/example_project/README.md
- projects/example_project/configs/fcos3d_dummy-resnet_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d.py
- projects/example_project/dummy/__init__.py
- projects/example_project/dummy/dummy_resnet.py
> [Community] Add Projects/ folder, and the first example project in `dev` branch

- mmdet3d/models/data_preprocessors/data_preprocessor.py
- mmdet3d/models/data_preprocessors/utils.py
> [Refactor] Refactor `voxelization` for faster speed

- mmdet3d/models/data_preprocessors/data_preprocessor.py
> [Fix] Fix key error

- README.md
> [Docs] Update the changelog in README

- .circleci/test.yml
- .github/workflows/merge_stage_test.yml
- .github/workflows/pr_stage_test.yml
- requirements/optional.txt
Add torch1.13 checking in CI.
2. The …
>  Add torch1.13 checking in CI

- .pre-commit-config.yaml
- docs/zh_cn/notes/benchmarks.md
- docs/zh_cn/notes/faq.md
> [Refactor] Fix mdformat version to support python3.6

- configs/imvoxelnet/README.md
- configs/imvoxelnet/imvoxelnet_2xb4_sunrgbd-3d-10class.py
- configs/imvoxelnet/imvoxelnet_8xb4_kitti-3d-car.py
- mmdet3d/models/dense_heads/__init__.py
- mmdet3d/models/dense_heads/imvoxel_head.py
- mmdet3d/models/detectors/imvoxelnet.py
- mmdet3d/models/necks/__init__.py
- mmdet3d/models/necks/imvoxel_neck.py
- tests/test_models/test_dense_heads/test_fcaf3d_head.py
- tests/test_models/test_dense_heads/test_imvoxel_head.py
- tests/test_models/test_detectors/test_imvoxelnet.py
Support imvoxelnet @ SUN RGB-D on 1.x branch.
- Refactor imvoxelnet detector, neck, head
- Add refactored config
- Add refactored unit test
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with …
> [Refactor] Support imvoxelnet @ SUN RGB-D on 1.x branch

- configs/pgd/pgd_r101-caffe_fpn_head-gn_16xb2-1x_nus-mono3d.py
> [Fix] rename `centers2d` to `centers_2d` in pgd config

- README.md
- README_zh-CN.md
- docs/en/changelog.md
- docs/en/faq.md
- mmdet3d/__init__.py
- mmdet3d/version.py
> Bump version to 1.0.0rc7

- mmdet3d/utils/util_distribution.py
- mmdet3d/version.py
> [Fix] dev lint error

- tools/train.py
> [Fix] Fix resume arg conflict.

- .gitignore
> [Enhancement] Update .gitignore

- .pre-commit-config-zh-cn.yaml
> [CI]: add .pre-commit-config-zh-cn.yaml borrowed from mmcv to assist in installing pre-commit

- .pre-commit-config.yaml
> [CI] Fix isort

- .pre-commit-config-zh-cn.yaml
- .pre-commit-config.yaml
> [CI] Use official isort in dev-1.x

- projects/DETR3D/configs/detr3d_r101_gridmask.py
- projects/DETR3D/configs/detr3d_r101_gridmask_cbgs.py
- projects/DETR3D/configs/detr3d_vovnet_gridmask_trainval_cbgs.py
fix detr3d 'custom_import' error
> [Fix] fix detr3d 'custom_import' error

- tools/analysis_tools/analyze_logs.py
Usage:
If users want to plot training parameters, take `lr` as an example:
```shell
python tools/analysis_tools/analyze_logs.py plot_curve ${JSON_FILE} --keys lr
```
If users want to plot evaluation metric, take `Overall_3D_AP11_moderate` as an example:
```shell
python tools/analysis_tools/analyze_logs.py plot_curve ${JSON_FILE} --keys Overall_3D_AP11_moderate --eval --eval-interval ${EVAL_INTERVAL}
```
Does the modification introduce …
> [Fix] Fix bugs in `analyze_logs`

- mmdet3d/models/decode_heads/decode_head.py
- mmdet3d/models/decode_heads/dgcnn_head.py
- mmdet3d/models/decode_heads/paconv_head.py
- mmdet3d/models/decode_heads/pointnet2_head.py
- mmdet3d/models/segmentors/base.py
- mmdet3d/models/segmentors/encoder_decoder.py
> [Refactor] Refactor `segmentor`

- mmdet3d/datasets/dataset_wrappers.py
- tests/test_datasets/test_dataset_wrappers.py
This PR is created to be consistent with `dataset_wrapper` implemented in [MMEngine](https://github.com/open-mmlab/mmengine/blob/main/mmengine/dataset/dataset_wrapper.py),
1. …
> [Refactor] Support lazy_init for `CBGSDataset`

- mmdet3d/datasets/pipelines/formating.py
Replace numpy transpose with torch permute to speed-up! related mmdet PR https://github.com/open-mmlab/mmdetection/pull/9533
If this PR introduces a new feature, it is better to list some use …
> [Feature] Replace numpy transpose with torch permute to speed-up

- tools/create_data.py
- The code added in #2065 may cause error when converting waymo dataset to kitti format with `tensorflow`. More details can be found in discussion #2095
If this PR introduces a new feature, it is …
> Revert #2065

- tools/create_data.py
- tools/dataset_converters/update_infos_to_v2.py
> [Feature] Update test set to v2 version

- mmdet3d/datasets/transforms/loading.py
- tests/test_datasets/test_semantickitti_dataset.py
- tests/test_datasets/test_transforms/test_loading.py
Can't set seg_3d_dtype to type such as 'np.int32' in config.
Modify seg_3d_dtype from dtype to str.
1. Pre-commit or other linting tools are used to fix the potential lint …
> [Fix] Modify seg_3d_dtype from dtype to str

- tests/test_datasets/test_transforms/test_transforms_3d.py
Fix PolarMix UT to contain instance point in testcase.
1. Pre-commit or other linting …
> [Fix] Fix PolarMix UT

- mmdet3d/models/data_preprocessors/data_preprocessor.py
- mmdet3d/models/voxel_encoders/voxel_encoder.py
Fix bugs in voxelization and preprocessors
1. Fix some bugs.
2. Support `torch.clamp()` in low torch version.
3. Add `point2voxel_map` for cylinder3d inference. …
> [Fix] Fix bugs in voxelization and preprocessors

- mmdet3d/datasets/transforms/transforms_3d.py
In pytorch1.6.0, 'torch' has no module named 'clip'. …
> [Enhance] use `torch.clamp` to be compatible with torch1.6

- mmdet3d/datasets/pipelines/formating.py
related [PR](https://github.com/open-mmlab/mmdetection3d/pull/2315)
1. Pre-commit or other linting tools are used to …
> [Fix] Dev branch fix to_tensor bug when array strides is negative

- mmdet3d/models/voxel_encoders/voxel_encoder.py
Two places:  `self.scatter = DynamicScatter(voxel_size, point_cloud_range, True)`
The variables are not used in their classes. …
> Remove unnecessary code about DynamicScatter

- docs/en/notes/contribution_guides.md
refer to https://github.com/open-mmlab/mmocr/blob/dev-1.x/docs/en/notes/contribution_guide.md …
> [Docs] Add contribution guides

- README.md
- README_zh-CN.md
> [Doc]: Add more social networking links(dev-1.x)

- tools/test.py
- tools/train.py
Related [PR](https://github.com/open-mmlab/mmediting/pull/1712). …
> [Fix] Dev branch fix accepting an unexpected argument local-rank in PyTorch 2.0

- .circleci/test.yml
- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- .github/workflows/merge_stage_test.yml
- .github/workflows/pr_stage_test.yml
- .github/workflows/test_mim.yml
Update docker image to ubuntu-22.04 due to [The Ubuntu 18.04 Actions runner image will begin deprecation on 2022/08/08 and will be fully unsupported by 2023/04/01](https://github.com/actions/runner-images/issues/6002)
If this …
> [CI] Fix CI

- .github/workflows/merge_stage_test.yml
2. The modification is covered by …
> [CI] Fix the version error of torch

- .circleci/test.yml
- .dev_scripts/diff_coverage_test.sh
- .github/workflows/merge_stage_test.yml
- .github/workflows/pr_stage_test.yml
- .github/workflows/test_mim.yml
- mmdet3d/visualization/local_visualizer.py
> [CI]Fix CI with `pip install wheel`

- .readthedocs.yml
This issue occurred in mmengine. The solution is to remove `.pdf` format and only support `epub` in readthedocs config. …
> [Docs] Fix readthedocs

- tools/test.py
> [Fix] Fix test local rank

- .github/workflows/merge_stage_test.yml
> [CI] Fix merge_stage CI

- mmdet3d/datasets/convert_utils.py
- mmdet3d/datasets/transforms/loading.py
- mmdet3d/datasets/transforms/transforms_3d.py
- mmdet3d/evaluation/metrics/kitti_metric.py
- mmdet3d/evaluation/metrics/waymo_metric.py
- mmdet3d/structures/bbox_3d/base_box3d.py
- mmdet3d/structures/points/base_points.py
- projects/PETR/petr/transforms_3d.py
- tests/test_structures/test_bbox/test_box3d.py
- tools/dataset_converters/create_gt_database.py
- tools/deployment/mmdet3d_handler.py
- tools/deployment/test_torchserver.py
> [Enhance] Support more tensor-like operations for data structures.

- mmdet3d/models/backbones/minkunet_backbone.py
- mmdet3d/models/layers/__init__.py
- mmdet3d/models/layers/torchsparse/torchsparse_wrapper.py
- mmdet3d/models/layers/torchsparse_block.py
- tests/test_models/test_layers/test_torchsparse/test_torchsparse_module.py
1. Register more torchsparse operation.
2. Add Bottleneck.
3. Add `**kwargs` for additional args. …
> [Enhance] Torchsparse block

- docs/en/get_started.md
- docs/zh_cn/get_started.md
> [Docs] Fix minkowski install

- projects/PETR/README.md
> [Docs] Update README.md of PETR

- configs/fcos3d/metafile.yml
> [Docs] Fix fcos meta

- tests/test_models/test_utils/test_utils.py
> [Fix] Fix array_converter ut

- docs/en/user_guides/dataset_prepare.md
- docs/zh_cn/user_guides/dataset_prepare.md
- tools/create_data.py
> [Fix] fix typo

- mmdet3d/datasets/transforms/loading.py
- mmdet3d/models/necks/second_fpn.py
- projects/DSVT/README.md
- projects/DSVT/configs/dsvt.py
- projects/DSVT/configs/dsvt_voxel032_res-second_secfpn_8xb1-cyclic-12e_waymoD5-3d-3class.py
- projects/DSVT/dsvt/__init__.py
- projects/DSVT/dsvt/dsvt.py
- projects/DSVT/dsvt/dsvt_head.py
- projects/DSVT/dsvt/dsvt_input_layer.py
- projects/DSVT/dsvt/dsvt_transformer.py
- projects/DSVT/dsvt/dynamic_pillar_vfe.py
- projects/DSVT/dsvt/map2bev.py
- projects/DSVT/dsvt/ops/ingroup_inds/ingroup_inds_op.py
- projects/DSVT/dsvt/ops/ingroup_inds/src/error.cuh
- projects/DSVT/dsvt/ops/ingroup_inds/src/ingroup_inds.cpp
- projects/DSVT/dsvt/ops/ingroup_inds/src/ingroup_inds_kernel.cu
- projects/DSVT/dsvt/res_second.py
- projects/DSVT/dsvt/utils.py
- projects/DSVT/setup.py
> [Feature] Support inference of DSVT in `projects`

- .dev_scripts/benchmark_train_models.txt
Remove PointRCNN in benchmark training since the potential bug in the training of PointRCNN …
> Remove PointRCNN in benchmark training

- tools/dataset_converters/nuscenes_unzip.sh
`unzip` cannot unpack tgz file.
1. Pre-commit or other linting tools are used to fix …
> [FIX] modify download script for nuscenes

- .circleci/test.yml
- .github/workflows/merge_stage_test.yml
- .github/workflows/pr_stage_test.yml
- .github/workflows/test_mim.yml
Update torch minimum version to 1.8.1 and torch maximum version to 2.0.0 in CI.
1. …
> [CI] Update CI

- README_zh-CN.md
> Update QR code

- mmdet3d/datasets/transforms/transforms_3d.py
> [Fix] Fix potential bug in `lasermix`

- .readthedocs.yml
> [Fix] Fix docs build error

- .circleci/test.yml
- .github/workflows/merge_stage_test.yml
> [Fix] CI min gpu version and GitHub merge test

- .circleci/docker/Dockerfile
- .circleci/test.yml
- mmdet3d/version.py
> Update version file and circleci for v1.3.0
