.github/CONTRIBUTING.md
.github/workflows/deploy.yml
docs/changelog.md
setup.py

Fix version bug when packaging pypi.

Fix version bug when packaging pypi

---

mmdet3d/ops/iou3d/iou3d_utils.py
mmdet3d/ops/iou3d/src/iou3d.cpp

Fix minor bugs encountered when computing iou3d with gpu while the specified cuda id is not default 0

Fix minor bugs of computing iou3d

---

mmdet3d/core/bbox/samplers/iou_neg_piecewise_sampler.py
mmdet3d/core/post_processing/box3d_nms.py
mmdet3d/models/dense_heads/free_anchor3d_head.py
mmdet3d/models/dense_heads/vote_head.py
mmdet3d/ops/iou3d/iou3d_utils.py

This PR fixes some warnings when using Pytorch-1.6. It adds `as_tuple=False` when using `torch.nonzero`.
It also fixes the bug of NMS introduced by https://github.com/open-mmlab/mmdetection3d/pull/69.

Fix warning of Pytorch-1.6

---

mmdet3d/ops/__init__.py
mmdet3d/ops/furthest_point_sample/__init__.py
mmdet3d/ops/furthest_point_sample/furthest_point_sample.py
mmdet3d/ops/furthest_point_sample/points_sampler.py
mmdet3d/ops/furthest_point_sample/src/furthest_point_sample.cpp
mmdet3d/ops/furthest_point_sample/src/furthest_point_sample_cuda.cu
mmdet3d/ops/furthest_point_sample/utils.py
mmdet3d/ops/pointnet_modules/point_sa_module.py
tests/test_pointnet_modules.py
tests/test_pointnet_ops.py

Feature_3dssd_FPS_With_Dist_OP

---

tools/data_converter/create_gt_database.py

fix_create_gt_database

---

mmdet3d/core/bbox/structures/cam_box3d.py

The cam_box3d's inherited init in base_box3d uses a different default origin. This PR fixes this minor bug.

[Fix]: Fix init in cam_box3d

---

configs/_base_/models/votenet.py
tools/convert_votenet_checkpoints.py

Fix issue #145 by  converting the keys in the checkpoints of votenet models.

[Fix]: add convert script for Votenet

---

mmdet3d/core/points/base_points.py
tools/data_converter/create_gt_database.py

* Fix bugs for the create_gt_database of kitti
* Fix bugs for '__get_item__' of BasePoints

[Fix]: create_gt_database

---

tools/data_converter/create_gt_database.py

* Fix the bug on the commit #211 for the create_gt_database in nuscenes

[Fix]: create_gt_database of nuscenes

---

mmdet3d/core/evaluation/indoor_eval.py
tests/test_indoor_eval.py

fix indoor_eval in case of less classes in prediction

---

tools/data_converter/nuscenes_converter.py

Remove unreachable lines

---

docs/getting_started.md

When I try to install mmdetection3d according to doc `getting_started.md`, I met some problem:
1. pytorch install comand in `e.g. 1` will install latest version not 1.5.0 as stated above.
2. mmcv-full install command failed with "Invalid version".
I correct these little problem and set step titles bold to make them more clear.

fix some problem in getting_started.md

---

mmdet3d/ops/furthest_point_sample/furthest_point_sample.py

When running the VoteNet demo on sunrgbd with:
```
python tools/test.py configs/votenet/votenet_16x8_sunrgbd-3d-10class.py checkpoints/votenet_16x8_sunrgbd-3d-10class_20200620_230238-4483c0c0.pth --show --show-dir ./data/votenet/show_results
```
I got an error in `mmdetection3d/mmdet3d/ops/furthest_point_sample/furthest_point_sample.py` because `points_xyz` was a tuple of size 4, but it was being unpacked into a tuple of size 3. I changed:
```
B, N, _ = points_xyz.size()
```
to
```
B, N = points_xyz.size()[:2]
```
and now everything works correctly.

Fixed issue unpacking size in furthest_point_sample

---

mmdet3d/ops/voxel/src/scatter_points_cuda.cu
tests/test_voxelize.py

Voxelization unit test

---

mmdet3d/datasets/kitti_dataset.py
tests/test_dataset/test_kitti_dataset.py

Fix a bug, Miss text file when generating test file which will be submitted to test server! #123

Fix miss text

---

mmdet3d/models/detectors/centerpoint.py
tests/test_models/test_heads/test_heads.py

Fixed bias=True bug triggered when using mmcv==1.2.6;
Deleted pdb breakpoint.

fix bug caused by mmcv upgrade; delete pdb breakpoint

---

mmdet3d/ops/voxel/scatter_points.py
mmdet3d/ops/voxel/src/scatter_points_cuda.cu
mmdet3d/ops/voxel/src/voxelization.h
tests/test_models/test_voxel_encoder/test_dynamic_scatter.py

The original version of DynamicScatter is less memory-efficient because it allocates a temporary canvas tensor with shape (N_batch, N_voxel, N_max-point, N_feat) before doing the feature reduction (max or mean reduction). 
And, it fails when N_feat > 16, because the CUDA kernel launch configuration with ```cp_threads = dim3(64, N_feat)``` means more than 1024 threads per block is needed, while 1024 threads per block are physically the upper limit for most GPU. 
https://github.com/open-mmlab/mmdetection3d/blob/a347ac75dfcc4767909bc9185c111448f526c3da/mmdet3d/ops/voxel/src/scatter_points_cuda.cu#L228

A faster & more memory-efficient implementation of DynamicScatter

---

mmdet3d/core/visualizer/open3d_vis.py
mmdet3d/core/visualizer/show_result.py
requirements/optional.txt
requirements/tests.txt
setup.cfg

Reduce the dependence of open3d

[Fix] Rewarp open3d

---

docs/index.rst
mmdet3d/models/dense_heads/anchor3d_head.py
mmdet3d/models/dense_heads/ssd_3d_head.py
mmdet3d/models/dense_heads/train_mixins.py
mmdet3d/models/roi_heads/bbox_heads/h3d_bbox_head.py
mmdet3d/models/roi_heads/mask_heads/primitive_head.py

[Fix]: Fix warning of deprecated usages of nonzero during training with pytorch 1.6 (#320 )
* fix warning caused by upgrade of pytorch by specifying as_tuple=Fasle

Fix nonzero warning

---

mmdet3d/ops/voxel/scatter_points.py
mmdet3d/ops/voxel/src/scatter_points_cuda.cu
mmdet3d/ops/voxel/src/voxelization.h

fix a bug that may cause compilation failure of dynamic voxelization when using GPUs with compute capability lower than 6.x
fix imperfection kernel code that may unintentionally discard valid points when input points count is larger than 50000 * 512 (nearly impossible though).

[Fix] fix a bug that may cause compilation failure of dynamic voxelization when using GPUs with compute capability lower than 6.x

---

mmdet3d/ops/__init__.py
mmdet3d/ops/gather_points/gather_points.py
mmdet3d/ops/knn/__init__.py
mmdet3d/ops/knn/knn.py
mmdet3d/ops/knn/src/knn.cpp
mmdet3d/ops/knn/src/knn_cuda.cu
setup.py
tests/test_models/test_common_modules/test_pointnet_ops.py

Reference from https://github.com/unlimblue/KNN_CUDA

[Feature] Support knn gpu op

---

configs/second/README.md
docs/changelog.md

The results of SECOND on Waymo do not match the log file. The results on README are too low.
README:
| [SECFPN]|5|3 Class|2x|8.12||58.0|53.5|51.5|48.3|log|
| above @ Car|||2x|8.12||58.5|57.9|51.6|51.1| |
| above @ Pedestrian|||2x|8.12||63.9|54.9|56.0|48.0| |
| above @ Cyclist|||2x|8.12||48.6|47.6|46.8|45.8| |
LOG:
{"mode": "val", "epoch": 24, "iter": 1977, "lr": 1e-05, "Vehicle/L1 mAP": 0.67149, "Vehicle/L1 mAPH": 0.66598, "Vehicle/L2 mAP": 0.58660, "Vehicle/L2 mAPH": 0.58173, "Pedestrian/L1 mAP": 0.68099, "Pedestrian/L1 mAPH": 0.59131, "Pedestrian/L2 mAP": 0.59516, "Pedestrian/L2 mAPH": 0.51546, "Sign/L1 mAP": 0.0, "Sign/L1 mAPH": 0.0, "Sign/L2 mAP": 0.0, "Sign/L2 mAPH": 0.0, "Cyclist/L1 mAP": 0.60655, "Cyclist/L1 mAPH": 0.59519, "Cyclist/L2 mAP": 0.58416, "Cyclist/L2 mAPH": 0.57321, …

[Fix] fix SECOND Waymo results

---

mmdet3d/ops/interpolate/three_nn.py

Currently this bug won't be triggered in the repo. However, when the indices calculated by ThreeNN participate in backwarding, there will be an error message: `RuntimeError: Expected isFloatingType(grads[i].scalar_type()) to be true, but got false.`
Please refer to https://github.com/facebookresearch/votenet/pull/72 and https://discuss.pytorch.org/t/custom-autograd-function-with-int-tensor-input/65907.

[Fix] Fix potential bug in ThreeNN

---

mmdet3d/ops/roiaware_pool3d/points_in_boxes.py

Avoid 4 dims points as the input of points_in_boxes functions

[Fixed] Fix issue #298

---

tools/train.py

Val in workflow is intended to show the losses on test set. This pr fixes a bug when adding val to workflow.
Still, val uses train-time data augmentations, which is not preferred. However, one can slightly modify the config files and train.py in order to use test-time data augmentations for val. Therefore we do not address the issue in this pr. Perhaps some refactors might be considered in the future regarding this issue (the test_mode meaning and pipeline overriding here are also a bit confusing)?

[Fix] Fix a bug when adding ('val', 1) to workflow

---

.github/workflows/build.yml
mmdet3d/ops/voxel/src/scatter_points_cuda.cu

In Pytorch 1.7, the cuda kernel of dynamic voxelization will cause compilation errors of `error: class "at::Tensor" has no member "max_values"` as mentioned in https://github.com/open-mmlab/mmdetection3d/issues/362. This PR changes to use tensor.max() to fix the error.
Resolves https://github.com/open-mmlab/mmdetection3d/issues/362

[Fix]: fix compilation error in pytorch 1.7

---

mmdet3d/ops/voxel/src/scatter_points_cuda.cu
tests/test_models/test_voxel_encoder/test_dynamic_scatter.py

- fix 'invalid configuration argument' error triggered by empty point input. test cases covering similar situations are added to test_dynamic_scatter.py as well.
trivial changes:
- switch to using torch::unique_dim to generate reduce mapping instead of calculating it from scratch.

[Fix] dynamic_scatter 'invalid configuration argument error' triggered by empty point input

---

mmdet3d/datasets/pipelines/loading.py
mmdet3d/datasets/pipelines/transforms_3d.py

Fix [issue#411](https://github.com/open-mmlab/mmdetection3d/issues/411), so that developers will understand the points during loading pipeline are instances of BasePoints class. They need to take out the tensor/coord/attribute of points in case some operations are not supported by BasePoints class.

[Fix] Fix point type errors in docstring in pipeline functions

---

mmdet3d/core/visualizer/open3d_vis.py
mmdet3d/core/visualizer/show_result.py

Similar to detection online visualization, I use open3d to show segmentation masks. The main difference here is that, in det, we can draw gt and pred bbox on top of scene_points, because they won't overlap too much with each other. However the drawing of seg requires per-point colorization, while scene_points often have their own colors. So we can't draw them together.
My solution is that, I set an offset for each seg mask and then draw them in a row. See examples below.

[Feature] Support online visualization of semantic segmentation results

---

data/scannet/README.md
data/scannet/batch_load_scannet_data.py
data/scannet/load_scannet_data.py
mmdet3d/datasets/scannet_dataset.py
tests/test_data/test_datasets/test_scannet_dataset.py
tools/data_converter/indoor_converter.py
tools/data_converter/scannet_data_utils.py

Convert network output prediction to original label_idx. Save each mask as a txt file.

[Feature] Support ScanNet test results submission to online benchmark

---

configs/3dssd/3dssd_kitti-3d-car.py
configs/_base_/models/3dssd.py
configs/_base_/schedules/cyclic_20e.py
configs/_base_/schedules/cyclic_40e.py
configs/_base_/schedules/mmdet_schedule_1x.py
configs/_base_/schedules/schedule_2x.py
configs/_base_/schedules/schedule_3x.py
configs/benchmark/hv_PartA2_secfpn_4x8_cyclic_80e_pcdet_kitti-3d-3class.py
configs/benchmark/hv_pointpillars_secfpn_3x8_100e_det3d_kitti-3d-car.py
configs/benchmark/hv_pointpillars_secfpn_4x8_80e_pcdet_kitti-3d-3class.py
configs/benchmark/hv_second_secfpn_4x8_80e_pcdet_kitti-3d-3class.py
configs/free_anchor/hv_pointpillars_regnet-1.6gf_fpn_sbn-all_free-anchor_strong-aug_4x8_3x_nus-3d.py
configs/free_anchor/hv_pointpillars_regnet-3.2gf_fpn_sbn-all_free-anchor_strong-aug_4x8_3x_nus-3d.py
configs/imvotenet/imvotenet_faster_rcnn_r50_fpn_2x4_sunrgbd-3d-10class.py
configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py
configs/nuimages/cascade_mask_rcnn_r50_fpn_coco-20e_20e_nuim.py
configs/nuimages/htc_r50_fpn_coco-20e_20e_nuim.py
configs/nuimages/htc_x101_64x4d_fpn_dconv_c3-c5_coco-20e_16x1_20e_nuim.py
configs/nuimages/mask_rcnn_r50_caffe_fpn_coco-3x_20e_nuim.py
configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py
docs/getting_started.md
docs/tutorials/config.md
docs/tutorials/customize_runtime.md
mmdet3d/__init__.py

Refer to https://github.com/open-mmlab/mmdetection/pull/4570#.

[Refactor] Customize runner type

---

mmdet3d/core/voxel/voxel_generator.py
mmdet3d/ops/spconv/include/spconv/point2voxel.h
mmdet3d/ops/voxel/src/voxelization_cpu.cpp
mmdet3d/ops/voxel/src/voxelization_cuda.cu

Fix issue #406 :
-  "break" leads to points missing during voxelization;
-  "continue" ensures the completeness of voxelization

[FIX]  fix the bug of missing points

---

mmdet3d/core/bbox/structures/box_3d_mode.py
mmdet3d/core/bbox/structures/cam_box3d.py
mmdet3d/core/bbox/structures/coord_3d_mode.py
mmdet3d/core/points/base_points.py
mmdet3d/datasets/pipelines/transforms_3d.py
tests/test_data/test_pipelines/test_augmentations/test_transforms_3d.py

Fix [issue#440](https://github.com/open-mmlab/mmdetection3d/issues/440). When filtering/sampling points in pipeline, perform the same actions on masks too.

[Enhance] Pipeline function process points and masks simultaneously

---

mmdet3d/models/fusion_layers/vote_fusion.py

Fix issue #448:
- Projection of 3D seed points to image sometimes results in out-of-range image indices (by 1 or 2 pixels)
- Clamp the image indices to be within bounds

[Fix] #448 Clamp 3D votes projections to image boundaries

---

mmdet3d/models/dense_heads/fcos_mono3d_head.py

Due to #283 fixing the inplace operation when adjusting the origin of 3D boxes, initializing CameraInstance3DBoxes will not change the input tensor for center. So we need to input the origin setting (0.5, 0.5, 0.5) again when initializing the 3D boxes at the modified code.

[Fix] Fix the origin setting when inference with FCOS3D head

---

configs/_base_/datasets/s3dis_seg-3d-13class.py
configs/_base_/datasets/scannet-3d-18class.py
configs/_base_/datasets/scannet_seg-3d-20class.py
docs/tutorials/config.md
mmdet3d/datasets/pipelines/loading.py
mmdet3d/datasets/s3dis_dataset.py
mmdet3d/datasets/scannet_dataset.py
tests/test_data/test_datasets/test_s3dis_dataset.py
tests/test_data/test_datasets/test_scannet_dataset.py
tests/test_data/test_pipelines/test_indoor_pipeline.py
tests/test_data/test_pipelines/test_indoor_sample.py
tests/test_data/test_pipelines/test_loadings/test_loading.py

The original implementation uses for-loop to convert every label, which is super slow in large scenes (e.g. S3DIS seg dataset without sub-sampling). I modify it to use matrix indexing, which could be faster. Matrix indexing is also a common practice in other 3D Seg repos.

[Enhance] Efficient implementation of PointSegClassMapping

---

docs/getting_started.md
mmdet3d/__init__.py
mmdet3d/datasets/builder.py
mmdet3d/datasets/pipelines/dbsampler.py
mmdet3d/datasets/pipelines/transforms_3d.py
mmdet3d/datasets/registry.py
mmdet3d/models/__init__.py
mmdet3d/models/builder.py
mmdet3d/models/fusion_layers/point_fusion.py
mmdet3d/models/fusion_layers/vote_fusion.py
mmdet3d/models/middle_encoders/pillar_scatter.py
mmdet3d/models/middle_encoders/sparse_encoder.py
mmdet3d/models/middle_encoders/sparse_unet.py
mmdet3d/models/registry.py
mmdet3d/models/voxel_encoders/pillar_encoder.py
mmdet3d/models/voxel_encoders/voxel_encoder.py
mmdet3d/ops/pointnet_modules/builder.py
mmdet3d/ops/pointnet_modules/point_sa_module.py
mmdet3d/ops/pointnet_modules/registry.py

Note: this requires MMCV>=1.3.1!

[Refactor] Use MMCV MODEL_REGISTRY

---

tests/test_models/test_detectors.py

This solves the oom problem in unit test correctly and should replace #481 . Shall we put every `simple_test` under the `test_models` folder to be under `torch.no_grad()`?

[Fix] Put simple_test under torch.no_grad() in unit test

---

.gitignore
README.md
README_zh-CN.md
docs/tutorials/customize_runtime.md

The ignored data folder should be `data/xxx` instead of `/data/xxx`.
MMDet no longer has `mmdet/core/optimizer`. Instead, they use optimizer from `mmcv`. I modify this part of docs accordingly.

[Fix] Typos in .gitignore & error in customize_runtime docs

---

demo/multi_modality_demo.py
demo/pcd_demo.py
mmdet3d/apis/inference.py
mmdet3d/core/visualizer/show_result.py

* Enabling visualization of the pcd demo results online
* Enabling visualization of the multi-modality demo results online
**Risk**: Whether to simultaneously visualize the point and image results online when visualizing multi-modality demo?

[Fix] enable visualization of the demo results online

---

tools/data_converter/sunrgbd_data_utils.py

When reading calibration files, both Rt and K are being stored as Rt values only. This should fix the issue.

[Fix] Fix for SUN RGB-D, when creating .pkl files

---

mmdet3d/core/visualizer/show_result.py

In #473, it [changed the default arg value of `mmdet3d.core.visualizer.show_result`](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/visualizer/show_result.py#L78), from `show=True` to `show=False`, which caused code `mmdet3d.models.detectors.{mvx_two_stage/base}.show_results` to broke (not showing the visualization even when `--show` is enabled during testing.

Fix: #473 changed default arg value for `show_result` and caused `--show` broke during testing

---

docker/Dockerfile
docs/getting_started.md
mmdet3d/__init__.py
mmdet3d/utils/collect_env.py

From mmdet3d 0.14.0, we will have MMSegmentation as our requirement. I add the version check in code and instructions about its installation in the docs.
Actually, the master branch of mmdet3d now is incompatible with MMSeg. Their newest version (0.13.0) has finished MMCV MODEL registry refactor while we haven't. Their earlier version will cause errors in training 3D segmentors. The best solution is to have our PR #378 merged as soon as possible.

[Enhance] Add MMSeg requirement in docs & code

---

mmdet3d/core/bbox/structures/coord_3d_mode.py

* Fixing the bug that the specified rt_matrix will be overwritten by fixed constant when converting from lidar to cam, or from cam to lidar, or from lidar to depth, or from depth to lidar.

[Fix] Converting point with specified rt_matrix

---

mmdet3d/datasets/nuscenes_dataset.py
mmdet3d/datasets/nuscenes_mono_dataset.py

Currently, for nuScenes dataset, some important metrics (which are the components of NDS) are not included in the logger output:
```
mATE: 0.4187
mASE: 0.2787
mAOE: 0.4978
mAVE: 0.2941
mAAE: 0.1783
```
Adding these to logger outputs will make it more convenient for the user to analyze the results.

[Enhance] Add more metrics to nuScenes logger outputs

---

mmdet3d/datasets/__init__.py
mmdet3d/datasets/pipelines/__init__.py
mmdet3d/datasets/pipelines/transforms_3d.py
tests/test_data/test_pipelines/test_augmentations/test_transforms_3d.py

A transform function used in 3D segmentation, that set colors of points to all zeros according to a probability. Used in PAConv's paper.

[Feature] Add `RandomDropPointsColor` transform

---

mmdet3d/datasets/__init__.py
mmdet3d/datasets/pipelines/__init__.py
mmdet3d/datasets/pipelines/transforms_3d.py
tests/test_data/test_pipelines/test_augmentations/test_transforms_3d.py

This transform function adds random noise to each point in a 3D scene, which is used in the PAConv segmentor's paper. In a word, its functionality is:
```
points[:, :3] += np.random.randn(points.shape[0], 3) * jitter_std
```
Current transform function can't achieve this functionality:
- [`ObjectNoise`](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/pipelines/transforms_3d.py#L274) adds noise to object points and bboxes, but we don't have bboxes in segmentation task
- [`GlobalRotScaleTrans`](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/pipelines/transforms_3d.py#L438) uses a same translation vector to all the points, and also involve bbox

[Feature] Add `RandomJitterPoints` transform

---

mmdet3d/datasets/custom_3d.py
mmdet3d/datasets/custom_3d_seg.py
mmdet3d/datasets/nuscenes_mono_dataset.py
mmdet3d/datasets/utils.py

See https://github.com/open-mmlab/mmdetection3d/pull/542#discussion_r637499596.
Currently, I only move the staticmethod `self._get_data()` to `utils.py` because the other two functions `self._get_pipeline()` and `self._extract_data()` involve many `self.xxx` calling.
A solution is to use utils functions that take `dataset` as input args, and call `dataset.xxx` as `self.xxx`. But I am not sure if this is a valid coding style? @Tai-Wang can you give me some advice?

[Enhance] Reuse some functions in `Datasets` loading data

---

mmdet3d/__init__.py

MMDet3D is compatibility with mmseg >= 0.13.0, including 0.14.0 which is their newest release.

[Fix] Fix mmseg max version requirement

---

mmdet3d/datasets/__init__.py
mmdet3d/datasets/pipelines/__init__.py
mmdet3d/datasets/pipelines/transforms_3d.py
tests/test_data/test_pipelines/test_augmentations/test_transforms_3d.py
tests/test_data/test_pipelines/test_loadings/test_loading.py

Now all functions under `mmdet3d/datasets/pipeline/` have their own unit tests.

[Enhance] Add missing unit tests for pipeline functions

---

tools/analysis_tools/analyze_logs.py

There are two errors I have encountered when using `analyze_logs.py` to plot eval metrics:
1. When the log is generated in an experiment that **resume** from a checkpoint, we won't have info in previous epochs in the json file. Thus we need to adjust the start epoch in `xs`. Current code assume we start from epoch 1 which is not always the case.
2. When an experiment is killed or stopped before eval, we won't have metric value in the last epoch. However, current code assumes it exists so will cause a length error. We judge if eval is performed in the last epoch and drop the last epoch in `xs` if not.
Described above.
No
No

[Fix] Fix potential bug in using `analyze_logs`

---

mmdet3d/core/bbox/structures/utils.py

Similar to Lidar2Cam conversion, we need a `-yaw - pi / 2` hacking to get correct boxes for visualization. No need to do so in evaluation because eval is performed between boxes wrapped in `NuScenesBox` class, which have same definition of rotation.

[Fix] Fix direction error caused by mono-3d box angle hacking

---

configs/imvoxelnet/README.md

Add ImVoxelNet README with checkpoint. More discussion in [#620#issuecomment-859575352](https://github.com/open-mmlab/mmdetection3d/issues/620#issuecomment-859575352).
You can upload the model and log to open-mmlab server and update the links.

[Enhance] Add README for ImVoxelNet

---

.github/workflows/build.yml
docker/Dockerfile
docs/getting_started.md
mmdet3d/__init__.py

MMDet3D is currently compatible with mmseg>=0.13.0, remove the max version limit.
Modify installation instruction to install mmdet 2.11.0.
**Edit**: we need to fix mmseg to 0.14.0 because of [this](https://github.com/open-mmlab/mmsegmentation/commit/db44d16e023fd248280943c0bac79b9b5ce11042) commit.

[Fix] Fix MMSeg max version

---

docs/datasets/scannet.md
docs/datasets/scannet_det.md

Add docs of ScanNet including:
- data preparation: explanation about raw data and annotations
- train pipeline: load data and pre-processing
- metrics: evaluation

Scannet doc

---

mmdet3d/datasets/pipelines/loading.py
tests/test_data/test_pipelines/test_loadings/test_load_images_from_multi_views.py

Fix issue #227. `LoadMultiViewImageFromFiles` is currently not used in the codebase. I simply unravel the stacked multi-view img to list because `DefaultFormatBundle` requires so (see [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/pipelines/formating.py#L44)).
This solution is better than PR #229 I think.

[Fix] Fix `LoadMultiViewImageFromFiles` to be compatible with `DefaultFormatBundle`

---

mmdet3d/core/bbox/structures/coord_3d_mode.py

Convert `rt_mat` in 'coord_3d_mode.py' from np.ndarray to torch.Tensor. Closes #707 
The `rt_mat` in 'coord_3d_mode.py' takes np.ndarray and torch.tensor types, but the conversion from np.ndarray to torch.Tensor is missing as further code assumes that `rt_mat` is a torch.Tensor type. So, conversion of `rt_mat` from np.ndarray to torch.tensor type is added! 
If so, please describe how it breaks the compatibility and how the …

[Fix] Convert rt_mat to torch.Tensor in Coord transform for compatibility

---

mmdet3d/datasets/pipelines/transforms_3d.py

Fix the `bev_range` initialization in ObjectRangeFilter according to the gt_bboxes_3d type. Closes #716 
The `bev_range` initialization in ObjectRangeFilter `__init__` is moved to `__call__` to check the gt_bboxes_3d coordinate system type (like LiDAR or CAM) and initialize it accordingly.
No
2. The modification is covered by complete unit tests. If not, please …

[Fix] Move bev_range to ObjectRangeFilter's call for consistency with gt_bboxes_3d type

---

docs/model_zoo.md
docs_zh-CN/model_zoo.md

* Add Chinese document of model_zoo
* Fix some typos of model_zoo in English document
* Add ImVoxelNet info into model_zoo

[Docs] Chinese Document of model_zoo

---

docs/useful_tools.md
mmdet3d/models/detectors/single_stage.py
mmdet3d/models/detectors/voxelnet.py
tools/analysis_tools/get_flops.py

Fix issue #731. Support FLOPs counter for MMDet3D models.
Modify the `get_flops.py` script from MMDet. Add `forward_dummy` function in some detector classes.
No.
See the docs for details.
4. The documentation has …

[Feature] Support FLOPs and Params calculation in MMDet3D

---

tools/analysis_tools/analyze_logs.py

A minor error when plotting eval results and `interval == 1`. If we abort training and then plot curve, the length of x-dim (epoch) and y-dim (some epoch) will be different.
Check if `interval == 1`.
No
N.A
4. The …

[Fix] Fix potential bug in using `analyze_logs.py`

---

mmdet3d/models/voxel_encoders/voxel_encoder.py

Fix #675 
Change to `in_channels += 1` when `with_distance=True`
Current MMDet3D never uses VFE layers with `with_distance=True`, so this PR won't affect our codebase.
N.A
4. The documentation has been modified …

[Fix] Fix wrong in_channels when with_distance=True in VFE layers

---

configs/groupfree3d/groupfree3d_8x4_scannet-3d-18class-L12-O256.py
configs/groupfree3d/groupfree3d_8x4_scannet-3d-18class-L6-O256.py
configs/groupfree3d/groupfree3d_8x4_scannet-3d-18class-w2x-L12-O256.py
configs/groupfree3d/groupfree3d_8x4_scannet-3d-18class-w2x-L12-O512.py

The size of a most simple groupfree3d ckpt is around 170MB, and there are by default 400 ckpts saved in one run, which will take about 70GB space. There is a high chance of disk space/quota exceed, which will terminate training.
I added  `max_keep_ckpts`  in groupfree3d configs.
If this …

[Fix] Add `max_keep_ckpts` for groupfree3d

---

data/scannet/README.md
data/scannet/extract_posed_images.py
docs/compatibility.md
docs/datasets/scannet_det.md
mmdet3d/datasets/scannet_dataset.py
tools/data_converter/scannet_data_utils.py

This PR aims to support RGB images on ScanNet for multi-view detector. More discussion in #620.
It is a bit WIP now as I also plan to add images to `ScanNetDataset`. For now I just adapted `SensReader` from original ScanNet [repo](https://github.com/ScanNet/ScanNet/tree/master/SensReader/python). Can you please check if we are ok with it? cc @Tai-Wang

[Enhance] Support RGB images on ScanNet for multi-view detector

---

docs/faq.md
docs_zh-CN/faq.md

* Add Chinese Document of faq
* Refine a typo in faq

[Docs] Chinese Document of faq

---

mmdet3d/models/dense_heads/groupfree3d_head.py

Refactoring Groupfree3D initialization methods based MMCV

[Enhance] GroupFree3d inherits BaseModule From MMCV

---

data/scannet/README.md
docs/datasets/scannet_det.md
docs/datasets/scannet_sem_seg.md

[Enhance] Add doc for ScanNet semantic segmentation data

---

docker/Dockerfile

Since `mmpycocotools` is deprecated in MMDet3D, I remove its installation from Dockerfile.

[Fix] Remove `mmpycocotools` installation from Dockerfile

---

.gitignore
MANIFEST.in
README.md
README_zh-CN.md
setup.cfg
setup.py

[Enhance] Support mim

---

docs/getting_started.md
docs_zh-CN/getting_started.md

Add getting_started.md chinese version.

[Docs] Add getting_started chinese version

---

configs/3dssd/3dssd_4x4_kitti-3d-car.py
mmdet3d/datasets/pipelines/transforms_3d.py

The first three coord of `gt_bboxes_3d_np` has been set to the gravity center [here](https://github.com/open-mmlab/mmdetection3d/blob/78f456216f101b5b684db754176e0def17ab9d49/mmdet3d/datasets/pipelines/transforms_3d.py#L1172). Then, we input the box and points to function `points_in_rbbox`. However, `points_in_rbbox` has a default params `origin=(0.5, 0.5, 0)` as shown [here](https://github.com/open-mmlab/mmdetection3d/blob/78f456216f101b5b684db754176e0def17ab9d49/mmdet3d/core/bbox/box_np_ops.py#L425), while the origin should be …

[Fix] Fix bug in `BackgroundPointsFilter`

---

tools/test.py

Only segmentation task requires `PALETTE`, while the original will cause `AttributeError` for detection dataset

[Fix] Fix bug in `tools/test.py`

---

mmdet3d/ops/iou3d/src/iou3d.cpp
mmdet3d/ops/iou3d/src/iou3d_kernel.cu
mmdet3d/ops/paconv/src/assign_score_withk_cuda.cu
mmdet3d/ops/voxel/src/voxelization_cpu.cpp

Fix #169, related to #551 , but the author does not respond.

[Fix] Fix compiling error on windows

---

configs/_base_/datasets/scannet-3d-18class.py
configs/groupfree3d/groupfree3d_8x4_scannet-3d-18class-L12-O256.py
configs/groupfree3d/groupfree3d_8x4_scannet-3d-18class-L6-O256.py
configs/groupfree3d/groupfree3d_8x4_scannet-3d-18class-w2x-L12-O256.py
configs/groupfree3d/groupfree3d_8x4_scannet-3d-18class-w2x-L12-O512.py
docs/compatibility.md
docs/datasets/scannet_det.md
docs/datasets/sunrgbd_det.md
docs_zh-CN/datasets/sunrgbd_det.md
docs_zh-CN/tutorials/config.md
mmdet3d/datasets/pipelines/transforms_3d.py
tests/test_data/test_pipelines/test_augmentations/test_transforms_3d.py
tests/test_data/test_pipelines/test_indoor_sample.py

`IndoorPointSample` is deprecated in favor of `PointSample`, so I replace them in the codebase. Also, there is a bug in `PointSample` now.
Replace `IndoorPointSample` with `PointSample` and fix a bug.
No
N.A
4. The …

[Enhance] Migrate to `PointSample` and enhance `PointSample` function

---

mmdet3d/models/dense_heads/groupfree3d_head.py
tests/test_models/test_detectors.py
tests/test_models/test_heads/test_heads.py

GroupFree-3D's config files are `8x4`, while in the unit test they are `8x8`. Fix them in this PR

[Fix] Fix wrong GF3D cfg file name in unit test

---

tools/analysis_tools/benchmark.py

[Fix] Fix `wrap_fp16_model` import

---

docs/datasets/scannet_det.md
docs/datasets/sunrgbd_det.md
docs_zh-CN/datasets/scannet_det.md
docs_zh-CN/datasets/sunrgbd_det.md

[Doc] Add Chinese doc for `scannet_det.md`

---

docs/datasets/waymo_det.md
docs_zh-CN/datasets/waymo_det.md

[Doc] Add Chinese doc for `waymo_det.md`

---

tools/create_data.py
tools/data_converter/lyft_converter.py

2D annotations are not used on Lyft, and there are some compatible problems due to support of monocular 3D detection on nuScenes. We prefer to deprecating that function (export_2d_annotations) to avoid unnecessary data preparation steps.
1. Remove exporting 2D annotations when preparing info for Lyft experiments.
2. Add a deprecated warning to export_2d_annotation in the lyft converter.

[Fix] Remove exporting 2D annotations on Lyft

---

docs/index.rst
docs_zh-CN/index.rst
docs_zh-CN/tutorials/index.rst

Inconsistency between English and Chinese `index.rst`.
If this PR introduces a new feature, it is better to list some use cases here, …

[Fix] Fix `index.rst` for Chinese docs

---

CITATION.cff
setup.py

Add citation files and update the authors' field of setup.py
No.

Add citation

---

mmdet3d/core/bbox/structures/cam_box3d.py
mmdet3d/core/bbox/structures/utils.py
mmdet3d/models/dense_heads/ssd_3d_head.py
tests/test_models/test_detectors.py
tests/test_utils/test_box3d.py

https://github.com/open-mmlab/mmdetection3d/pull/677#discussion_r695494114
If this PR introduces a new feature, it is better to list …

[Fix] Change `axis=1` behaviour of `rotation_3d_in_axis`

---

mmdet3d/ops/voxel/src/scatter_points_cuda.cu
tests/test_models/test_voxel_encoder/test_dynamic_scatter.py

[Fix] Dynamic scatter bug fix: Discarded the first voxel by mistake when all input points have valid coors #768

---

demo/mono_det_demo.py
demo/multi_modality_demo.py
demo/pc_seg_demo.py
demo/pcd_demo.py

fixed visuliaztion typos

---

docs/2_new_data_model.md
docs_zh-CN/2_new_data_model.md

* Add Chinese Document of 2_new_data_model
* Fix a typo error of English Document of 2_new_data_model

[Docs] Chinese Document of 2_new_data_model

---

mmdet3d/core/bbox/__init__.py
mmdet3d/core/bbox/structures/__init__.py
mmdet3d/core/bbox/structures/utils.py
mmdet3d/models/dense_heads/fcos_mono3d_head.py
tests/test_utils/test_utils.py

Move the transformation from image to camera in the FCOS3D to mmdet3d/core such that it is more convenient for other classes or functions to use it.
Add deprecation warning for the static method pts2Dto3D in the FCOS3D.
Rename it as points_img2cam and move it into mmdet3d/core.
If …

[Refactor] Refactor the transformation from image to camera coordinates

---

configs/_base_/models/fcos3d.py
mmdet3d/core/bbox/coders/__init__.py
mmdet3d/core/bbox/coders/fcos3d_bbox_coder.py
mmdet3d/models/dense_heads/fcos_mono3d_head.py
tests/test_utils/test_bbox_coders.py

Support FCOS3D BBox Coder to simplify related decoding operations in the detection head.
- Add FCOS3D BBox Coder and use its functions to replace operations in the detection head.
- Modify the related configs accordingly.
- Add unit tests for the introduced bbox coder.
If so, …

[Feature] FCOS3D BBox Coder

---

mmdet3d/ops/voxel/src/voxelization.h
mmdet3d/ops/voxel/src/voxelization_cuda.cu
mmdet3d/ops/voxel/voxelize.py
tests/test_models/test_voxel_encoder/test_voxelize.py

Small enhancement -- reimplement hard voxelization and make it faster at the cost of deterministic property
It is now an optional feature and is disabled by default. Set `deterministic=False` inside `Voxelization` config to enable it. It only works for hard voxelization and has no effect when using dynamic voxelization.
Performance comparison:
| conf | training iter time tested on | iter time before| iter time after|
|:-------:|:-----------------------------------------:|:----------------------:|:---------------------:|
| [pointpillars-kitti-3class](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py) | 2080Ti<br>bs=6 | 0.340 | 0.303 |
| [pointpillars-kitti-car](https://github.com/open-mmlab/mmdetection3d/blob/mast …

[Enhancement] faster but nondeterministic version of hard voxelization

---

mmdet3d/core/visualizer/show_result.py
tools/create_data.py

1. Incorrect default value for show_result proposed buy #1032 
2. While converting Waymo test data set, the split is wrong, proposed by #1016 
1. Change the default value in show_result func to be consistent with docstring.
2. change ` test_mode=(split == 'test')) ` to ` test_mode=(split == 'testing')) `.
no
n/a
3. If the modification …

[Fix] Fix default show value in show_result function and a typo in waymo_data_prep

---

mmdet3d/datasets/nuscenes_mono_dataset.py

Fix incorrect velocity indexing when formatting boxes on nuScenes.
Note that this fix can affect the specific evaluation result for mAVE but won't affect the final NDS because mAVE is usually larger than 1 for monocular 3D detectors (at least not affect the currently supported mono3D models).
Only fix the incorrect velocity indexing when changing nuscenes boxes to `CameraInstance3DBoxes`.
If so, please describe how it breaks the …

[Fix] Fix incorrect velo indexing when formatting boxes on nuScenes

---

mmdet3d/core/visualizer/show_result.py
mmdet3d/datasets/kitti_mono_dataset.py
mmdet3d/datasets/utils.py

There are bugs while visualize results of mono3d model while multi-gpu testing in test.py.
Fix the bugs while visualize results of mono3d model while multi-gpu testing in test.py.
no
n/a
4. The documentation has been …

[Fix] Fix Visualization problem while multi-gpu testing for monocular 3D object detection model

---

docs/useful_tools.md
docs_zh-CN/useful_tools.md
mmdet3d/datasets/kitti_dataset.py
mmdet3d/datasets/lyft_dataset.py
mmdet3d/datasets/nuscenes_dataset.py
mmdet3d/datasets/nuscenes_mono_dataset.py
mmdet3d/datasets/waymo_dataset.py

If you are running test in remote server without GUI, the online visualization is not supported, fow now, once `show=False`, it will not only disable show online, but also disable saving meshlab results into out_dir.
support only save output meshlab results while evaluating mAP on remote server
no
n/a
3. If the modification has …

[Enhance] support only save output meshlab results while evaluating mAP on remote server

---

tools/analysis_tools/get_flops.py
tools/misc/browse_dataset.py
tools/test.py
tools/train.py

As MMCV already supports custom_imports. The entrypoints in MMDet3D no longer need to handle the custom_imports manually. 
Clean unnecessary custom_imports in entrypoints
no
n/a
4. The documentation has been modified …

[Enhance] Clean unnecessary custom_imports in entrypoints

---

mmdet3d/apis/inference.py

#1055 
Explicitly setting the cuda device before model.to(device)

Explicitly setting torch.cuda.device at init_model

---

docker/Dockerfile
docs/getting_started.md
model-index.yml

It would be nice to be able to play with bleeding edge features when using docker, but currently this is not possible. For example, PGD config is missing from docker image, because code in master is cloned.
Instead of cloning the master branch in Dockerfile, now we just copy the repository contents. In v1.0.0-dev0 branch, we can see PGA in Docker container, because contents of the current branch are copied. Sine copying cannot be done outside docker build context, the build command had to be modified a bit by adding the -f option as shown in the .md-file.
I don't see this as a breaking change. If there are CI builds that try to build the docker image in this repo, then the build commands in CI-yml files may need update. (But only if v1.0.0-dev0 gets merged to master).
- …

Add PGD to Docker image

---

requirements/mminstall.txt

Fix the upper bound of mmcv version in the mminstall requirements.
Change the latest mmcv version from v1.4.0 to v1.5.0. …

[Fix] Fix the upper bound of mmcv version in the mminstall requirements

---

mmdet3d/core/bbox/structures/base_box3d.py
mmdet3d/core/bbox/structures/cam_box3d.py
mmdet3d/core/bbox/structures/utils.py

add local yaw property in base_box3d and camera_box3d.
add local yaw property in base_box3d and camera_box3d. …

[Enhance] Add local yaw (alpha) property

---

README.md
README_zh-CN.md
configs/imvoxelnet/README.md

Update ImVoxelNet citation from arxiv to WACV 2022 following [openaccess](https://openaccess.thecvf.com/WACV2022).

[Enhance] update imvoxelnet citation

---

setup.py

Deprecate the support for "python setup.py test" motivated by [here](https://github.com/open-mmlab/mmcv/pull/1637).
Update setup.py by removing unnecessary dependency.
1. …

[Fix] Deprecate the support for "python setup.py test"

---

requirements/runtime.txt
setup.cfg

Since from 0.54.0, numba does not support cuda9.0, we lock the number version to 0.53.0, which supports both cuda9.0 and …

[Fix] numba version lock

---

configs/3dssd/README.md
configs/centerpoint/README.md
configs/dgcnn/README.md
configs/dynamic_voxelization/README.md
configs/fcos3d/README.md
configs/free_anchor/README.md
configs/groupfree3d/README.md
configs/h3dnet/README.md
configs/imvotenet/README.md
configs/imvoxelnet/README.md
configs/mvxnet/README.md
configs/nuimages/README.md
configs/paconv/README.md
configs/parta2/README.md
configs/pgd/README.md
configs/point_rcnn/README.md
configs/pointnet2/README.md
configs/pointpillars/README.md
configs/regnet/README.md
configs/second/README.md
configs/smoke/README.md
configs/ssn/README.md
configs/votenet/README.md

Update README format.
Update README format.
If this PR introduces a new feature, it is better to list some use cases here, and update …

[Fix] Update README format

---

docs/en/datasets/nuscenes_det.md
docs/zh_cn/datasets/nuscenes_det.md

As pointed out in #1190 , the explanations of cam_intrinsic are missing in the nuScenes dataset documentation.
Add missing explanations of cam_intrinsic in the nuScenes dataset documentation.
If so, please describe how it breaks the compatibility and how the downstream projects …

[Fix] Add missing explanations of cam_intrinsic in the nuScenes dataset doc

---

configs/_base_/models/point_rcnn.py
mmdet3d/core/bbox/samplers/iou_neg_piecewise_sampler.py
mmdet3d/models/dense_heads/point_rpn_head.py

Fix PointRCNN bugs.
1. Add `points_in_boxes` to avoid the involvement of boxes without any points when training.
2. Remove the constraint of compulsory involvement of negative samples when in R-CNN training stage.
3. Not use `match_low_quality`.
If so, please describe how it …

[Fix] Fix potential gradient divergence of corner_loss in PointRCNN

---

mmdet3d/ops/gather_points/gather_points.py
mmdet3d/ops/gather_points/src/gather_points.cpp
mmdet3d/ops/gather_points/src/gather_points_cuda.cu
mmdet3d/ops/group_points/group_points.py
tests/test_models/test_common_modules/test_pointnet_ops.py

Thanks for the great repository! 
I try to train PointNet in fp16 mode but the function/modules don't allow HALF input, so I made some changes. 
- I changed '''gather_points''' ops to allow Half input because this operation is just indexing corresponding values. And I add two lines in the '''tests/test_models/test_common_modules/test_pointnet_ops.py''' file.
- I add '''force_fp32''' in the '''mmdet3d/ops/group_points/group_points.py''', because it relates to knn or ball_query operations.
If this PR introduces a new feature, it is better to list …

fix bug to allow pointnet to train in fp16

---

mmdet3d/apis/inference.py

Hello, when I support mmdet3d in mmdeploy, I find if my device == 'cpu', error:
`Traceback (most recent call last):
File "/home/PJLAB/shenkun/workspace/mmdetection3d/demo/pcd_demo.py", line 44, in <module>
main()
File "/home/PJLAB/shenkun/workspace/mmdetection3d/demo/pcd_demo.py", line 29, in main
model = init_model(args.config, args.checkpoint, device=args.device)
File "/home/PJLAB/shenkun/workspace/mmdetection3d/mmdet3d/apis/inference.py", line 76, in init_model
torch.cuda.set_device(device)
File "/home/PJLAB/shenkun/anaconda3/envs/pt1.8/lib/python3.8/site-packages/torch/cuda/__init__.py", line 259, in set_device
device = _get_device_index(device)
File "/home/PJLAB/shenkun/anaconda3/envs/pt1.8/lib/python3.8/site-packages/torch/cuda/_utils.py", line 31, in _get_device_index
raise …

[Fix]fix init_model to support 'device=cpu'

---

mmdet3d/models/dense_heads/point_rpn_head.py
tests/test_data/test_datasets/test_kitti_dataset.py
tests/test_data/test_datasets/test_kitti_mono_dataset.py
tests/test_data/test_datasets/test_waymo_dataset.py
tests/test_models/test_common_modules/test_dgcnn_modules.py
tests/test_models/test_detectors.py
tests/test_models/test_heads/test_heads.py
tests/test_models/test_heads/test_roi_extractors.py
tests/test_models/test_necks/test_necks.py

Fix unittest with GPU
Refine a series of unittest.
2. The modification is covered by complete unit …

[Fix] Fix unittest with GPU

---

tools/train.py

Due to the code design in MMDetection3D, we support auto resume form the latest checkpoint automatically when mmdet version>=2.20.0 for 3D detection model and mmsegmentation version>= 0.21.0 for 3D segmentation model.
Due to the code design in MMDetection3D, we support auto resume form the latest checkpoint automatically when mmdet version>=2.20.0 for 3D detection model and mmsegmentation version>= 0.21.0 for 3D segmentation model. …

[Enhance] Resume from the latest checkpoint automatically

---

mmdet3d/models/voxel_encoders/__init__.py
mmdet3d/models/voxel_encoders/pillar_encoder.py

[Fix] Fix DynamicPillarFeaureNet incorrect index caused by modifications of PillarFeatureNet

---

mmdet3d/core/visualizer/open3d_vis.py

Fix a bug about visualize yaw. When I visualize pointpillars by `demo/pcd_demo.py`, I find box yaw is erred and then I fix it.
None
python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin
configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py
https://download.openmmlab.com/mmdetection3d/v1.0.0_models/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth
--show
--device
cuda:0

[Fix]fix bug about box visualize yaw

---

mmdet3d/core/bbox/structures/base_box3d.py
mmdet3d/core/post_processing/__init__.py
mmdet3d/core/post_processing/box3d_nms.py
mmdet3d/core/post_processing/merge_augs.py
mmdet3d/models/dense_heads/centerpoint_head.py
mmdet3d/models/dense_heads/parta2_rpn_head.py
mmdet3d/models/dense_heads/point_rpn_head.py
mmdet3d/models/roi_heads/bbox_heads/parta2_bbox_head.py
mmdet3d/models/roi_heads/bbox_heads/point_rcnn_bbox_head.py
tests/test_utils/test_box3d.py

Remove `mmcv.iou3d` from `mmdetection3d`.
- `iou3d_boxes_overlap_bev_forward` -> `box_iou_rotated.box_iou_rotated`
- `iou_3d.nms_bev` -> `nms.nms_rotated`
- `iou_3d.nms_normal_bev` -> `nms.nms`
For now only `iou3d_boxes_overlap_bev_forward` -> `box_iou_rotated.box_iou_rotated` is done. `Nms` can be replaced in this PR in the future or in the other PR.
May be only due to some float tolerance.

[Enhance] Remove mmcv.iou3d from mmdetecion3d

---

mmdet3d/models/dense_heads/point_rpn_head.py

Fix #1409 . Now `tests/test_models/test_heads/test_heads.py::test_point_rcnn_rpnhead_getboxes` and `tests/test_models/test_detectors.py::test_point_rcnn` are passed successfully.
No

[Fix] NMS for Point RCNN

---

docs/en/getting_started.md
mmdet3d/models/backbones/__init__.py
mmdet3d/models/backbones/mink_resnet.py
tests/test_models/test_backbones.py

Support MinkowskiEngine as a part of FCAF3D development plan. This sparse convolution backend can be used for other detection or segmentation methods.
Add docs about MinkowskiEngine installation and MinkResNet model with test.
No.

[Feature] Support MinkowskiEngine with MinkResNet

---

tools/test.py

After pr #1388, if the user installed mmdet version is not the newest, err:
```
Traceback (most recent call last):
File "tools/test.py", line 259, in
main()
File "tools/test.py", line 151, in main
setup_multi_processes(cfg)
File "/home//.local/lib/python3.8/site-packages/mmdet/utils/setup_env.py", line 30, in setup_multi_processes
if 'OMP_NUM_THREADS' not in os.environ and cfg.data.workers_per_gpu > 1:
File "/home/*/.local/lib/python3.8/site-packages/mmcv/utils/config.py", line 49, in getattr
raise ex
```
fix test.py to import setup_multi_processes from mmdet3d to resolve back-compatibility.

[Bug]fix mmdet bc breaking

---

mmdet3d/apis/train.py
mmdet3d/datasets/pipelines/test_time_aug.py
mmdet3d/utils/__init__.py
mmdet3d/utils/misc.py

Fix registry potential bug, this modification is only an experimental version.
1. Pre-commit or other linting tools …

[Fix] Fix registry potential bug

---

docs/en/conf.py

By default, myst-parser did not parse links to anchor tags in markdown files, making these hyperlinks become raw texts in docs. This PR updates myst's configuration to enable this feature.
related PR https://github.com/open-mmlab/mmrotate/pull/305

[DOC]Configure Myst-parser to parse anchor tag

---

mmdet3d/core/post_processing/box3d_nms.py
tests/test_utils/test_merge_augs.py
tests/test_utils/test_nms.py

Fix bugs introduced in #1403. This is also related to [mmcv#1902](https://github.com/open-mmlab/mmcv/pull/1902).
Fix bugs, add tests from mmcv.

[Fix] Bugs in nms

---

docker/Dockerfile

I resolved <https://github.com/open-mmlab/mmdetection3d/issues/1501>.
[Current Dockerfile](https://github.com/open-mmlab/mmdetection3d/blob/v1.0.0rc2/docker/Dockerfile) does not specify MMCV. It may cause problem of compatibility.
So, I add to specify compatible MMCV version.
```shell
git clone https://github.com/atinfinity/mmdetection3d.git -b fixed-mmcv-compatibility
cd mmdetection3d
docker build -t mmdetection3d:1.0.0rc2 -f docker/Dockerfile .
```
```shell
docker run -it --rm --gpus all mmdetection3d:1.0.0rc2 bash
```
```shell
python mmdet3d/utils/collect_env.py 
sys.platform: linux
Python: 3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.24
GCC: gcc …
```

[Fix] fixed compatibility of MMCV

---

mmdet3d/core/bbox/structures/depth_box3d.py

This fix is separated from FCAF3D PR #1547 after a small discussion with @ZwwWayne.
While working on that PR I've checked my FCAF3D checkpoints for ScanNet, SUN RGB-D and S3DIS from `mmdetectiontion3d==0.15.0`. And for ScanNet and S3DIS metrics were exactly the same, unlike SUN RGB-D with mAP@0.5 less then expected by ~3%. After some debugging I saw that the model is fine, but the difference is caused by the evaluation function. And basically the difference is in `BaseInstance3DBoxes.overlaps`. The difference is not that big, i.e. `test_indoor_eval` successfully passes with this fix and without it. But, maybe it is a bug.
As I understand we call `mmcv.ops.box_iou_rotated` in `BaseInstance3DBoxes.overlaps` and this function is designed for anti-clockwise heading angle. So it is probably ok …

[Fix] Flip yaw angle for DepthInstance3DBoxes.overlaps

---

mmdet3d/datasets/custom_3d.py

The function [`get_ann_info`](https://github.com/open-mmlab/mmdetection3d/blob/14c5ded49dd5df7a52368bd54c32a003c2521e1d/mmdet3d/datasets/custom_3d.py#L149) in [Custom3DDataset](https://github.com/open-mmlab/mmdetection3d/blob/14c5ded49dd5df7a52368bd54c32a003c2521e1d/mmdet3d/datasets/custom_3d.py#L17) is supposed to return a dict with the following keys (it says it also in the function's documentation): `gt_bboxes_3d`, `gt_labels_3d`, `gt_names`, but `gt_names `wasn't included in the return dict.
I was trying to add a custom dataset in mmdetection3d, and I was getting this KeyError telling me that there wasn't the key "gt_names" in the annotations.
The error was coming from [this line](https://github.com/open-mmlab/mmdetection3d/blob/master/tools/data_converter/create_gt_database.py#L245) …

[Fix] Fixed bug on Custom3DDataset

---

mmdet3d/core/bbox/structures/depth_box3d.py

Revert #1548 as it didn't fix any bugs.
Remove `DepthInstance3DBoxes.overlaps`.
Yes but it is a bug fix only in `dev` branch.

[Fix] Revert #1548

---

data/sunrgbd/README.md
docs/en/compatibility.md
docs/en/datasets/sunrgbd_det.md
docs/zh_cn/datasets/sunrgbd_det.md
tools/create_data.py
tools/data_converter/indoor_converter.py
tools/data_converter/sunrgbd_data_utils.py

Voxel-based methods use more then 50000 points and are able to use unlimited amount of points. So we skip point sampling during preprocessing and keep the possibility for users to sample any amount with `PointSample` further.
Add `num_points` to SUN RGB-D preprocessing script.
Users may update there `*.pkl` files, however the metrics of all models will be the same. The minimal changes may be due to randomness in sampling.

[Enhance] Remove 50000 points sampling from SUN RGB-D preprocessing

---

mmdet3d/datasets/__init__.py
mmdet3d/datasets/pipelines/__init__.py
mmdet3d/datasets/pipelines/transforms_3d.py
tests/test_data/test_pipelines/test_augmentations/test_transforms_3d.py

Update the transformation in mmdet3d to support requirements in the multi-camera 3D object detection
1. Support multi-view wrapper to wrap the transformation designed for single-view situation into multi-view situation.
2. Support random rotation and return the rotation angle.
3. Support random crops with a limited range and return the cropping ROI.
--
--
1. Pre-commit or other linting tools are used to fix the potential lint issues. Done
4. The modification is covered by complete unit tests. If not, please add more unit test to …

[Feature] Add pipelines for BEVDet

---

mmdet3d/models/middle_encoders/pillar_scatter.py

Motivation
Just better description in PointPillarScatter.
Modification
The original description of voxel_features is (N, M, C), which indeed is (N, C)
BC-breaking (Optional)
NO
Use cases (Optional)
NO
Checklist
Pre-commit or other linting tools are used to fix the potential lint issues.
The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
If the modification has potential influence on downstream projects, this PR should be tested with downstream projects.
The documentation has been modified accordingly, like docstring or example tutorials.
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, …

Update description of Args: voxel_features

---

docs/en/compatibility.md
tools/data_converter/s3dis_data_utils.py

Very few objects (not more than one per scene) are missed due to a bug in S3DIS preprocessing.
Just add `+ 1` to fix a bug.
The users need to regenerate S3DIS annotations. However we do not have 3d object detection models on S3DIS for now.

[Fix] missing objects in S3DIS preprocessing

---

mmdet3d/datasets/pipelines/test_time_aug.py
mmdet3d/models/backbones/mink_resnet.py
mmdet3d/models/dense_heads/fcaf3d_head.py
mmdet3d/models/detectors/dynamic_voxelnet.py
mmdet3d/models/detectors/mink_single_stage.py

MinkowskiEngine is an extra requirement. We do not want to spam not using MinkowskiEngine users with warnings from all python files where it is imported (on every run of mmdetection3d).
Just remove warning when MinkowskiEngine is not installed.
No.

[Fix] Remove MinkowskiEngine ImportError warnings

---

mmdet3d/core/visualizer/show_result.py

See #1721 
Added check for empty `pred_labels` tensor.

Fix visualization for empty prediction labels

---

.github/workflows/deploy.yaml
configs/_base_/schedules/cosine.py
configs/_base_/schedules/cyclic-20e.py
configs/_base_/schedules/cyclic-40e.py
configs/_base_/schedules/mmdet-schedule-1x.py
configs/_base_/schedules/schedule-2x.py
configs/_base_/schedules/schedule-3x.py
configs/_base_/schedules/seg-cosine-100e.py
configs/_base_/schedules/seg-cosine-150e.py
configs/_base_/schedules/seg-cosine-200e.py
configs/_base_/schedules/seg-cosine-50e.py
configs/h3dnet/h3dnet_8xb3_scannet-seg.py
configs/imvotenet/imvotenet_stage2_8xb16_sunrgbd-3d.py
configs/parta2/PartA2_hv_secfpn_8xb2-cyclic-80e_kitti-3d-3class.py
configs/point_rcnn/point-rcnn_8xb2_kitti-3d-3class.py
configs/pointpillars/pointpillars_hv_fpn_sbn-all_8xb2-2x_lyft-3d-range100.py
configs/pointpillars/pointpillars_hv_fpn_sbn-all_8xb2-2x_lyft-3d.py
configs/pointpillars/pointpillars_hv_secfpn_sbn-all_16xb2-2x_waymo-3d-3class.py
configs/pointpillars/pointpillars_hv_secfpn_sbn-all_16xb2-2x_waymo-3d-car.py
configs/pointpillars/pointpillars_hv_secfpn_sbn-all_16xb2-2x_waymoD5-3d-car.py
configs/pointpillars/pointpillars_hv_secfpn_sbn-all_8xb2-2x_lyft-3d-range100.py
configs/pointpillars/pointpillars_hv_secfpn_sbn-all_8xb2-2x_lyft-3d.py
configs/regnet/pointpillars_hv_regnet-400mf_fpn_sbn-all_8xb2-2x_lyft-3d.py
configs/regnet/pointpillars_hv_regnet-400mf_fpn_sbn-all_range100_8xb2-2x_lyft-3d.py
configs/second/second_hv_secfpn_sbn-all_16xb2-2x_waymoD5-3d-3class.py
configs/ssn/ssn_hv_secfpn_sbn-all_16xb2-2x_lyft-3d.py
configs/votenet/votenet_8xb16_sunrgbd-3d.py
configs/votenet/votenet_8xb8_scannet-3d.py

Add auto lr scope  in  schedule cfg. …

[Refactor] Add auto lr in cfg

---

mmdet3d/visualization/local_visualizer.py

add output dir check, `output_file` is actually an directory.
https://github.com/open-mmlab/mmdeploy/pull/1039 needs it.
add `os.mkdir`
4. The documentation has been modified accordingly, like docstring or example …

feat(local_visualizer.py): add check dir exist

---

mmdet3d/datasets/custom_3d_seg.py

This PR is used to fix the issue #1457

[Fix] Fix seg vis bug due to wrong parameter passing

---

configs/imvoxelnet/imvoxelnet_8xb4_kitti-3d-car.py
mmdet3d/evaluation/metrics/kitti_metric.py
mmdet3d/models/detectors/base.py
mmdet3d/models/detectors/fcos_mono3d.py
mmdet3d/models/detectors/groupfree3dnet.py
mmdet3d/models/detectors/h3dnet.py
mmdet3d/models/detectors/imvotenet.py
mmdet3d/models/detectors/imvoxelnet.py
mmdet3d/models/detectors/mvx_two_stage.py
mmdet3d/models/detectors/single_stage.py
mmdet3d/models/detectors/single_stage_mono3d.py
mmdet3d/models/detectors/two_stage.py
mmdet3d/models/detectors/votenet.py

Fix some bugs in ImVoxelNet and KittiMetric, simplify the configs of ImVoxelNet and replace all `convert_to_datasample` with `add_pred_to_datasample` for keeping consistency with `mmdet` …

[Fix] Fix ImVoxelNet and KittiMetric & refactor configs of ImVoxelNet

---

mmdet3d/datasets/det3d_dataset.py
mmdet3d/datasets/transforms/formating.py
mmdet3d/engine/hooks/visualization_hook.py
mmdet3d/visualization/local_visualizer.py
tests/test_engine/test_hooks/test_visualization_hook.py

[Fix] fix vis hook bug and ut

---

mmdet3d/datasets/transforms/compose.py
mmdet3d/datasets/transforms/dbsampler.py
mmdet3d/datasets/transforms/formating.py
mmdet3d/datasets/transforms/loading.py
mmdet3d/datasets/transforms/test_time_aug.py
mmdet3d/datasets/transforms/transforms_3d.py

[Enhance]: Add typehints for dataset transforms and fix potential bug for `PointSample`

---

mmdet3d/datasets/convert_utils.py
mmdet3d/structures/bbox_3d/box_3d_mode.py
mmdet3d/structures/bbox_3d/cam_box3d.py
mmdet3d/structures/bbox_3d/lidar_box3d.py
tools/create_data.py
tools/dataset_converters/kitti_data_utils.py
tools/dataset_converters/update_infos_to_v2.py
tools/dataset_converters/waymo_converter.py

Add the code of generating cam_sync_labels on waymo dataset. It is used for cam only 3d object detection on the waymo dataset.

[Feature] Add the code of generating cam_sync_labels on waymo dataset

---

mmdet3d/visualization/local_visualizer.py
tools/misc/browse_dataset.py

[Fix] fix point cloud loop visualization error

---

mmdet3d/datasets/convert_utils.py

[Fix]: Fix dataset converter bug

---

mmdet3d/structures/bbox_3d/base_box3d.py

The Tensor-like class should support additional arguments input for `to` function, such as `non_blocking`
This change is to be compatible with the latest MMEngine: https://github.com/open-mmlab/mmengine/blob/main/mmengine/structures/base_data_element.py#L465. If not, an error occurs.
If so, please describe how it breaks the compatibility and how the downstream projects …

[Fix] Fix `to` function of BaseInstance3DBoxes

---

docs/en/changelog.md
mmdet3d/models/roi_heads/bbox_heads/point_rcnn_bbox_head.py
mmdet3d/models/roi_heads/point_rcnn_roi_head.py
tests/test_models/test_heads/test_parta2_bbox_head.py

Fix PonitRCNN GPU memory occupancy problem. Issue #1907  …

Fix PonitRCNN GPU memory occupancy problem

---

tools/dataset_converters/waymo_converter.py

The image writing using mmcv is through decoding and encoding, then saving as a .'jpg' image. It will lose some image information.
Our original solution: decoding and encoding the image info, and then saving it as a .'png' image. It will not lose image info but cause a large storage footprint since the '.png' encoding.
New Solution: writing the image as a file in 'wb' mode like this [PR](https://github.com/open-mmlab/mmdetection3d/blob/dev/tools/data_converter/waymo_converter.py#L146), which is merged in the dev branch.
The …

[Fix] Fix image saving in the waymo preprocessing script.

---

mmdet3d/models/task_modules/samplers/iou_neg_piecewise_sampler.py

Fix https://github.com/open-mmlab/mmdetection3d/issues/2004
update piece_expected_num iou_neg_piecewise_sampler.py …

[Fix] Fix `piece_expected_num` in IoUNegPiecewiseSampler

---

.circleci/config.yml
projects/example_project/README.md
projects/example_project/configs/fcos3d_dummy-resnet-caffe-dcn_fpn_head-gn_8xb2-1x_nus-mono3d.py
projects/example_project/dummy/__init__.py
projects/example_project/dummy/dummy_resnet.py

This PR adds a new projects/ folder, which will be a place for some experimental models/features. Implementations inside might be not quite perfect but already fine to produce some exciting results. We hope that this PR can help us better embrace the contribution from our community. We also add the first example project to illustrate what we expect a good project to have.
Does the modification introduce changes that break the back-compatibility of the downstream …

[Community] Add 'Projects/' folder, and the first example project

---

tools/dataset_converters/update_infos_to_v2.py

Fix `update_infos_to_v2` functions to work with Windows paths.
Use `pathlib` instead of relying on `split('/')` which does not work for Windows paths.
Nothing should break since it is only contained inside the functions.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream …

fix paths in `update_infos_to_v2` on Windows by using `pathlib`

---

mmdet3d/models/backbones/mink_resnet.py
mmdet3d/models/dense_heads/fcaf3d_head.py
mmdet3d/models/detectors/mink_single_stage.py
mmdet3d/visualization/local_visualizer.py

1. When running on env without open3d, it will not raise an error unless it uses our visualization.
2. The warning will not raise when running tasks not related to MinkowskiEngine. Otherwise, it's so ugly.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility …

[Enhance] Pretty log about MinkowskiEngine and running rightly on env without open3d

---

docs/en/getting_started.md
docs/zh_cn/getting_started.md

there is a error in getting-start doc, config file is misspelling …

fix the getting started documentation error

---

tools/create_data.py

When process `create_dataset.py` for waymo, will stuck in `torch.einsum`
Add `multiprocessing.set_start_method("spawn")` setting at the beginning of the code. 
After added this code, will process successful.
```shell
sys.platform: linux
Python: 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:49:35) [GCC 10.4.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.5, V11.5.119
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.12.0
PyTorch compiling details: PyTorch built with:
- GCC 9.3
- C++ Version: 201402
- Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
- Intel(R) MKL-DNN v2.6.0 (Git Hash …
```

[Fix] Fix stuck in `torch.einsum` when create dataset

---

mmdet3d/evaluation/metrics/waymo_metric.py

Now, after evaluation on Waymo, the type of results is dict(dict). It's not supported in MMEngine. It should be a dict. …

[Fix] Fix the error of data type in waymo metric

---

docs/en/advanced_guides/supported_tasks/lidar_det3d.md
docs/zh_cn/advanced_guides/supported_tasks/lidar_det3d.md
docs/zh_cn/getting_started.md

[Doc] Update tutorial of `lidar_det3d`

---

tools/dataset_converters/update_infos_to_v2.py

lidar2cam error in update_infos_to_v2.py for nus and lyft dataset.
In the latest info version, we save the transformation from lidar to camera coordinate system with a unified transformation matrix, but the original implementation does not multiply the rotation matrix with the translation matrix, leading to errors in transformation matrices. This PR fixes this problem, and users should re-convert info with the new script.
This problem does not affect the currently supported models in 1.x but may yield potential errors for …

[Fix] lidar2cam error in update_infos_to_v2.py for nus and lyft dataset.

---

mmdet3d/structures/bbox_3d/base_box3d.py

[Fix] Fix memory overflow in the rotated box IoU calculation

---

mmdet3d/engine/hooks/visualization_hook.py
tools/test.py

Fix https://github.com/open-mmlab/mmdetection3d/issues/2112
Add visualization task parameter in the hook
1. Pre-commit or other linting tools are used to fix the potential lint …

[Fix] Fix missing parameter in `Det3DVisualizationHook`

---

docs/en/advanced_guides/customize_dataset.md
docs/zh_cn/advanced_guides/customize_dataset.md

**note**: We need to build `1.1` documentation for english version and `dev-1.x` documentation for chinese version to avoid broken links.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this …

[Docs] Update `customize_dataset` documentation

---

tools/dataset_converters/update_infos_to_v2.py

Fix numpy value assignment error. I was updating an info.pkl generated from an older mmdet3d of v1.0.0rc2, via command
` python tools/dataset_converters/update_infos_to_v2.py --dataset nuscenes --pkl-path ./data/nus_rc2/nuscenes_infos_val.pkl --out-dir ./data/nus_v2`
I encountered this error:
`File "tools/dataset_converters/update_infos_to_v2.py", line 336, in update_nuscenes_infos
lidar2sensor[:3, 3] = -1 * np.matmul(rot.T, trans.reshape(3, 1))`
`ValueError: could not broadcast input array from shape (3,1) into shape (3,)`
In update_infos_to_v2.py, I simply changed all `lidar2sensor[:3, 3] = -1 * np.matmul(rot.T, trans.reshape(3, 1))` to `lidar2sensor[:3, 3:4] = -1 * np.matmul(rot.T, trans.reshape(3, 1))`

[Fix] Fix numpy ValueError in update_infos_to_v2.py

---

mmdet3d/apis/train.py
mmdet3d/utils/__init__.py
mmdet3d/utils/util_distribution.py
tools/test.py
tools/train.py

Mmdet3d support PyTorch backend on MLU (with Cambricon PyTorch).
Motivation
Support Cambricon MLU device for PyTorch backend.
Modification
mmdet3d/utils/util_distribution.py 、mmdet3d/utils/init.py : add build_ddp, build_dp and get_device functions to use different devices.
mmdet3d/apis/train.py 、 tools/test.py、tools/train.py : use build_ddp, build_dp to support mlu backend.
Checklist
Pre-commit or other linting tools are used to fix the potential lint issues.
The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
If the modification has potential influence on downstream projects, this PR should be tested with downstream projects.
The documentation has been modified accordingly, like docstring or example tutorials.

[Feature] Support MLU backend on the dev branch

---

configs/fcos3d/fcos3d_r101-caffe-dcn_fpn_head-gn_8xb2-1x_nus-mono3d_finetune.py
configs/pgd/pgd_r101-caffe_fpn_head-gn_16xb2-1x_nus-mono3d.py
configs/pgd/pgd_r101-caffe_fpn_head-gn_16xb2-1x_nus-mono3d_finetune.py
configs/pgd/pgd_r101-caffe_fpn_head-gn_16xb2-2x_nus-mono3d.py
configs/pgd/pgd_r101-caffe_fpn_head-gn_16xb2-2x_nus-mono3d_finetune.py
configs/pgd/pgd_r101-caffe_fpn_head-gn_4xb3-4x_kitti-mono3d.py
configs/pgd/pgd_r101_fpn-head_dcn_16xb3_waymoD5-fov-mono3d.py
configs/pgd/pgd_r101_fpn-head_dcn_16xb3_waymoD5-mono3d.py
configs/pgd/pgd_r101_fpn-head_dcn_16xb3_waymoD5-mv-mono3d.py

[Fix] fix part of fcos3d and pgd configs

---

configs/_base_/datasets/kitti-mono3d.py
mmdet3d/evaluation/metrics/kitti_metric.py
mmdet3d/evaluation/metrics/nuscenes_metric.py
mmdet3d/evaluation/metrics/waymo_metric.py

Add format_only option for nuScenes and Waymo evaluation

---

docs/en/advanced_guides/customize_models.md
docs/en/advanced_guides/customize_runtime.md
docs/zh_cn/advanced_guides/customize_models.md
docs/zh_cn/advanced_guides/customize_runtime.md

[Docs] Update `customize_models` and `customize_runtime`

---

tools/create_data.py
tools/dataset_converters/kitti_data_utils.py
tools/dataset_converters/update_infos_to_v2.py
tools/dataset_converters/waymo_converter.py

Currently, mmdet3d-dev1.x cannot generate waymo_info_test.pkl for testing or testing_camera_only properly.
This PR is aiming at fixing it.
1.  create_data.py
- Add function call `create_ImageSets_img_ids()` to generate ImageSets according to data in kitti_format/
- Add function call `update_pkl_infos('waymo', out_dir=out_dir, pkl_path=test_path)` to update test info generated in `kitti.create_waymo_info_file(...)`
2. kitti_data_utils.py
- Detach `timestamp` collecting from `velodyne_path` collecting. `timestamp` is very important link between kitti_format data and tfrecords data, so we still need to collect it even if no lidar data provided. PR #2179 also need timestamps in waymo_infos_*.pkl to generate idx2metainfo.pkl
3. updata_infos_to_v2.py
- Use `dict.get(key)` methods instead of …

Support waymo_info_test.pkl and ImageSets generating

---

mmdet3d/datasets/transforms/formating.py

dev-1.x change np.transpose to torch.permute. Related mmdet PR https://github.com/open-mmlab/mmdetection/pull/9533.
If this PR introduces a new feature, it is better to list some use cases here, …

[Feature] dev-1.x change np.transpose to torch.permute for speed up

---

projects/TR3D/README.md
projects/TR3D/configs/tr3d.py
projects/TR3D/configs/tr3d_1xb16_s3dis-3d-5class.py
projects/TR3D/configs/tr3d_1xb16_scannet-3d-18class.py
projects/TR3D/configs/tr3d_1xb16_sunrgbd-3d-10class.py
projects/TR3D/tr3d/__init__.py
projects/TR3D/tr3d/axis_aligned_iou_loss.py
projects/TR3D/tr3d/mink_resnet.py
projects/TR3D/tr3d/rotated_iou_loss.py
projects/TR3D/tr3d/tr3d_head.py
projects/TR3D/tr3d/tr3d_neck.py
projects/TR3D/tr3d/transforms_3d.py

Add TR3D detector in ScanNet, SUN RGB-D and S3DIS to `projects/TR3D`.
No

[Feature] Add TR3D detector to projects

---

mmdet3d/datasets/seg3d_dataset.py
mmdet3d/datasets/transforms/__init__.py
mmdet3d/datasets/transforms/transforms_3d.py
tests/test_datasets/test_transforms/test_transforms_3d.py

[Feature] Support `LaserMix` augmentation

---

mmdet3d/core/bbox/coders/centerpoint_bbox_coders.py
mmdet3d/models/dense_heads/centerpoint_head.py

**1、When using mixed precision, the average precision of centerpoint is incorrect in evaluation.**
Screenshot of the error:
**2、When the torch version<1.11, an error will be reported when executing the centerpoint model:**
The error message is:
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
This happens at centerpoint_head.py line542, due to center_int is saved on cuda, but feature_map_size is saved on the CPU.
``` python
if not (0 <= center_int[0] < feature_map_size[0]
and 0 <= center_int[1] < feature_map_size[1]):
continue
```
A more intuitive example:
``` python
>>> import torch
>>> torch.__version__
'1.8.0'
>>> a = torch.tensor([1])
>>> b = torch.tensor([2]).to('cuda')
>>> a<b
Traceback (most recent call last):
File …
```

[Fix] Fix issue of precision error under mixed precision on centerpoint.

---

projects/CenterFormer/centerformer/centerformer_backbone.py

mmdet3d coordinates are `xyzlwhr`, while in CenterFormer, `l` and `w` are opposite. This should be the same as mmdet3d coordinates.
4. The documentation has been modified accordingly, like docstring or example …

centerformer coordinates correspondence of gt box length and width

---

mmdet3d/apis/train.py
mmdet3d/utils/util_distribution.py
tools/test.py

Support train and test on Ascend NPU for mmdetection3d. 
+  Allow to get Ascend NPU device in get_device function.
+  Automatically enable fp16 when use Ascend NPU, since the NPU currently only supports mixed precision.
Not involved.
We have successfully run centerpoint on the NPU device, and the accuracy can be consistent with the GPU. We will supplement the corresponding documents and provide logs later.
config:centerpoint_02pillar_second_secfpn_4x8_cyclic_20e_nus.py
result:

[Feature] Support training and testing on Ascend NPU

---

.pre-commit-config-zh-cn.yaml
mmdet3d/models/backbones/pointnet2_sa_msg.py
mmdet3d/models/layers/pointnet_modules/builder.py

…Net2SAMSG
- the original .pre-commit-config-zh-cn.yaml is not equal to pre-commit-config.yaml, it makes code change after commit when using precommit.
- add mmdet3d/models/backbones/pointnet2_sa_msg typehints and fix warnings
- remove some repos in .pre-commit-config-zh-cn.yaml
- add mmdet3d/models/backbones/pointnet2_sa_msg.py typehints
- add location in …

[Fix] Update pre-commit-config-zh-cn.yaml and add typehints for PointNet2SAMSG

---

mmdet3d/utils/setup_env.py

Registry docs are now under Advanced Tutorials.
Changed doc location. I was looking for the docs and had to go find them myself.
Updated the doc link for Registry in mmengine
No, no breaking changes
3. If the modification has …

mmdet3d Docs update for registry location

---

tools/create_data.py

[Fix] fix bug when updating sunrgbd info to v2 version

---

docker/Dockerfile

Fix docker build issue. The present docker file is giving `cd: can't cd to /mmdetection` error while building 
change the folder name from mmdetection to mmdetection3d 
4. The documentation has been modified …

change cd to mmdetection3d from mmdetection to avoid docker build error

---

README.md
README_zh-CN.md

[Docs] Add links of MMagic and MMPretrain in ReadMe

---

mmdet3d/core/bbox/structures/base_box3d.py
mmdet3d/models/dense_heads/train_mixins.py

When I run:
``` shell
python tools/train.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py
```
I got such log:
``` log
File "/home/ubuntu/workspace/datang/mmdetection/mmdet/core/utils/misc.py", line 30, in multi_apply
return tuple(map(list, zip(*map_results)))
File "/home/ubuntu/workspace/datang/mmdetection3d/mmdet3d/models/dense_heads/train_mixins.py", line 142, in anchor_target_3d_single
assigner, current_anchors, gt_bboxes[gt_per_cls, :],
File "/home/ubuntu/workspace/datang/mmdetection3d/mmdet3d/core/bbox/structures/base_box3d.py", line 327, in __getitem__
b = self.tensor[item]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```
It seems that the `gt_bboxes[gt_per_cls, :]` is wrong about slicing and item tensor …

Fix device and slice

---

requirements/docs.txt

This PR is created to fix the bug when building docs due to the high version of `urllib3`. …

[Docs] Limit urllib3 version for docs building

---

mmdet3d/datasets/convert_utils.py

[Fix] AttributeError: 'LineString' object has no attribute 'exterior'

---

mmdet3d/models/middle_encoders/pillar_scatter.py
mmdet3d/models/middle_encoders/sparse_encoder.py
mmdet3d/models/middle_encoders/sparse_unet.py
mmdet3d/models/middle_encoders/voxel_set_abstraction.py
mmdet3d/models/voxel_encoders/pillar_encoder.py
mmdet3d/models/voxel_encoders/utils.py
mmdet3d/models/voxel_encoders/voxel_encoder.py

Add middle_encoder and voxel_encoder type hint to the code and make it more readable.
add type hints to mmdet3d/model/middle_encoders and mmdet3d/model/voxel_encoder

[Feature] Add middle_encoder and voxel_encoder type hint

---

mmdet3d/models/data_preprocessors/data_preprocessor.py
mmdet3d/models/data_preprocessors/utils.py

[Enhance] Support to modify `non_blocking` parameters.

---

README.md
README_zh-CN.md
docs/en/notes/changelog.md

[Docs] Update README

---

mmdet3d/__init__.py
mmdet3d/datasets/transforms/formating.py
mmdet3d/engine/hooks/visualization_hook.py
mmdet3d/visualization/local_visualizer.py
requirements/runtime.txt

[Fix] Fix indoor det visualization

---

requirements/runtime.txt
tests/test_apis/test_inferencers/test_lidar_seg3d_inferencer.py

[Fix]Fix open3d version bug for CI

---

mmdet3d/configs/centerpoint/centerpoint_pillar02_second_secfpn_8xb4_cyclic_20e_nus_3d.py
mmdet3d/configs/centerpoint/centerpoint_voxel01_second_secfpn_8xb4_cyclic_20e_nus_3d.py
mmdet3d/configs/minkunet/minkunet34_w32_torchsparse_8xb2_laser_polar_mix_3x_semantickitti.py
mmdet3d/configs/mvxnet/mvxnet_fpn_dv_second_secfpn_8xb2_80e_kitti_3d_3class.py
mmdet3d/configs/pgd/pgd_r101_caffe_fpn_head_gn_4xb3_4x_kitti_mono3d.py
mmdet3d/configs/votenet/votenet_8xb8_scannet_3d.py

In the newest mmengine version, we may use `read_base()` instead of `if '_base_'`.
1. Pre-commit or other linting …

[Fix] Update new config type

---

docs/en/advanced_guides/datasets/nuscenes.md
docs/zh_cn/advanced_guides/datasets/nuscenes.md

I was learning to use `mmdetction3d`. When I was trying to use sample codes in the tutorial of NuScenes Dataset, the samples were not accessible from the dataset by index. I looked into the tracebacks and found the `train_pipeline` has not been quite updated. To avoid similar problem other beginners may encounter, I want to update the tutorial
Update the `train_pipeline` …

[Docs] Add BEV-based detection pipeline in NuScenes Dataset tutorial

---

mmdet3d/configs/_base_/models/cylinder3d.py
mmdet3d/configs/cylinder3d/__init__.py
mmdet3d/configs/cylinder3d/cylinder3d_4xb4-3x_semantickitti.py
mmdet3d/configs/cylinder3d/cylinder3d_8xb2-laser-polar-mix-3x_semantickitti.py

Add new configuration files for Cylinder3D
Add one file in `mmdet3d/configs/_base_/models` called `mmdet3d/configs/_base_/models/cylinder3d.py` , and two file in `mmdet3d/configs/cylinder3d` which used to train and test.
1. Passed Pre-commit.
2. Finished train and test on A4000-16G, only modify train batchsize to 2 as out of memory and epoch to 1.
3. The logs and epoch is available here:链接：[百度网盘](https://pan.baidu.com/s/12X3rqE4fwED0_pDteuV5kw?pwd=zee2)提取码：zee2 
4. If there is anything to correct, please tell me.

[CodeCamp2023-516]Add new configuration files for Cylinder3D

---

mmdet3d/models/dense_heads/free_anchor3d_head.py

Fix support for devices other than Cuda.
The mmdet3d/models/dense_heads/free_anchor3d_head.py file is modified. …

[Fix] Fix support for devices other than Cuda in FreeAnchor3DHead

---

projects/PETR/README.md
projects/PETR/petr/petr_head.py

I am trying to run PETR project through mmdetction3d, but I found that the implementation is obsoleted
I updated the document of PETR project to quickly run a training and testing script.
And I updated the PETR head to adapt to the v2 dataset format.

Dev 1.x Adapt PETR to mmcv v2 version dataset 
